IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'ERPXL_GO')
BEGIN
  CREATE DATABASE ERPXL_GO;
END
GO

USE ERPXL_GO;
GO

-- create schema if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'CDN')
BEGIN
  EXEC('CREATE SCHEMA CDN');
END
GO

CREATE TABLE [CDN].[Dostawy](
	[Dst_GIDTyp] [smallint] NULL,
	[Dst_GIDFirma] [int] NULL,
	[Dst_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[Dst_GIDLp] [smallint] NULL,
	[Dst_TrnTyp] [smallint] NULL,
	[Dst_TrnFirma] [int] NULL,
	[Dst_TrnNumer] [int] NULL,
	[Dst_TrnLp] [smallint] NULL,
	[Dst_SubTrnLp] [smallint] NULL,
	[Dst_TwrTyp] [smallint] NULL,
	[Dst_TwrFirma] [int] NULL,
	[Dst_TwrNumer] [int] NULL,
	[Dst_TwrLp] [smallint] NULL,
	[Dst_KsiegowaNetto] [decimal](15, 2) NULL,
	[Dst_KsiegowaBrutto] [decimal](15, 2) NULL,
	[Dst_RzeczywistaNetto] [decimal](15, 2) NULL,
	[Dst_KosztKsiegowy] [decimal](15, 2) NULL,
	[Dst_KosztRzeczywisty] [decimal](15, 2) NULL,
	[Dst_Cecha] [varchar](255) NULL,
	[Dst_Ean] [varchar](40) NULL,
	[Dst_DataW] [int] NULL,
	[Dst_Ilosc] [decimal](15, 4) NULL,
	[Dst_DstTStamp] [int] NULL,
	[Dst_Polozenie] [varchar](64) NULL,
	[Dst_CCKTyp] [smallint] NULL,
	[Dst_CCKFirma] [int] NULL,
	[Dst_CCKNumer] [int] NULL,
	[Dst_CCKLp] [smallint] NULL,
	[Dst_WspFin] [decimal](10, 4) NULL,
	[Dst_KosztUstalono] [tinyint] NULL,
	[Dst_TpAId] [int] NULL,
	[Dst_ZewnetrznySys] [int] NULL,
	[Dst_ZewnetrznyId] [int] NULL,
	[Dst_OplataSpozFlaga] [tinyint] NULL,
  CONSTRAINT [Dst_Primary] PRIMARY KEY CLUSTERED ([Dst_GIDNumer])
)
GO

CREATE TABLE [CDN].[KntAdresy](
	[KnA_GIDTyp] [smallint] NULL,
	[KnA_GIDFirma] [int] NULL,
	[KnA_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[KnA_GIDLp] [smallint] NULL,
	[KnA_KntTyp] [smallint] NULL,
	[KnA_KntFirma] [int] NULL,
	[KnA_KntNumer] [int] NULL,
	[KnA_KntLp] [smallint] NULL,
	[KnA_DataArc] [int] NULL,
	[KnA_Akronim] [varchar](20) NULL,
	[KnA_Wysylkowy] [tinyint] NULL,
	[KnA_Nazwa1] [varchar](50) NULL,
	[KnA_Nazwa2] [varchar](50) NULL,
	[KnA_Nazwa3] [varchar](250) NULL,
	[KnA_KodP] [varchar](10) NULL,
	[KnA_Miasto] [varchar](30) NULL,
	[KnA_Ulica] [varchar](30) NULL,
	[KnA_Adres] [varchar](30) NULL,
	[KnA_NipE] [varchar](20) NULL,
	[KnA_Nip] [varchar](20) NULL,
	[KnA_NipPrefiks] [varchar](2) NULL,
	[KnA_Regon] [varchar](20) NULL,
	[KnA_Pesel] [varchar](11) NULL,
	[KnA_KontoDostawcy] [varchar](50) NULL,
	[KnA_KontoOdbiorcy] [varchar](50) NULL,
	[KnA_Kraj] [varchar](2) NULL,
	[KnA_Powiat] [varchar](30) NULL,
	[KnA_Gmina] [varchar](30) NULL,
	[KnA_Wojewodztwo] [varchar](30) NULL,
	[KnA_RegionCRM] [int] NULL,
	[KnA_GLN] [varchar](13) NULL,
	[KnA_Telefon1] [varchar](30) NULL,
	[KnA_Telefon2] [varchar](30) NULL,
	[KnA_Fax] [varchar](30) NULL,
	[KnA_Modem] [varchar](30) NULL,
	[KnA_Telex] [varchar](30) NULL,
	[KnA_EMail] [varchar](255) NULL,
	[KnA_BnkTyp] [smallint] NULL,
	[KnA_BnkFirma] [int] NULL,
	[KnA_BnkNumer] [int] NULL,
	[KnA_BnkLp] [smallint] NULL,
	[KnA_NrRachunku] [varchar](50) NULL,
	[KnA_LastModL] [int] NULL,
	[KnA_Odleglosc] [decimal](10, 2) NULL,
	[KnA_NRB] [smallint] NULL,
	[KnA_NiePublikuj] [smallint] NULL,
	[KnA_Domyslny] [smallint] NULL,
	[KnA_DokumentTozsamosci] [varchar](50) NULL,
	[KnA_DataWydania] [int] NULL,
	[KnA_OrganWydajacy] [varchar](50) NULL,
	[KnA_RolnikRyczaltowy] [tinyint] NULL,
	[KnA_StanPostep] [tinyint] NULL,
	[KnA_PlatnikVat] [tinyint] NULL,
	[KnA_GPSSz] [decimal](9, 6) NULL,
	[KnA_GPSDl] [decimal](9, 6) NULL,
	[KnA_GPSDataPobrania] [int] NULL,
	[KnA_GPSGodzinaPobrania] [int] NULL,
	[KnA_KnaPierwotny] [int] NULL,
	[KnA_KnaArchiwizowanego] [int] NULL,
	[KnA_Osoba] [smallint] NULL,
	[KnA_Opis] [varchar](2000) NULL,
	[KnA_Anonim] [tinyint] NULL,
	[KnA_AdresBank] [tinyint] NULL,
	[KnA_MetodaKasowa] [tinyint] NULL,
	[KnA_GUID] [varchar](41) NULL,
	[KnA_GUIDdane] [varchar](41) NULL,
	[KnA_VatDataRejestracji] [int] NULL,
	[KnA_VatDataOdmowy] [int] NULL,
	[KnA_VatDataPrzywrocenia] [int] NULL,
	[KnA_VatDataUsuniecia] [int] NULL,
	[KnA_VatDataSprawdzenia] [int] NULL,
	[KnA_KrajSiedziby] [varchar](2) NULL,
	[KnA_TypPOS] [smallint] NULL,
	[KnA_GUIDEmail] [varchar](41) NULL,
	[KnA_GUIDTelefon] [varchar](41) NULL,
	[KnA_UlicaCDC] [varchar](60) NULL,
	[KnA_NrDomuCDC] [varchar](10) NULL,
	[KnA_NrMieszkaniaCDC] [varchar](10) NULL,
	[KnA_CharsetANSI] [tinyint] NULL,
  CONSTRAINT [KnA_Primary] PRIMARY KEY CLUSTERED ([KnA_GIDNumer])
)
GO

CREATE TABLE [CDN].[KntGrupyDom](
	[KGD_GIDTyp] [smallint] NOT NULL,
	[KGD_GIDFirma] [int] NULL,
	[KGD_GIDNumer] [int] NOT NULL,
	[KGD_GIDLp] [smallint] NULL,
	[KGD_GrOTyp] [smallint] NULL,
	[KGD_GrOFirma] [int] NULL,
	[KGD_GrONumer] [int] NULL,
	[KGD_GrOLp] [smallint] NULL,
	[KGD_Kod] [varchar](40) NULL,
  CONSTRAINT [KGD_Primary] PRIMARY KEY CLUSTERED ([KGD_GIDTyp], [KGD_GIDNumer])
)
GO

CREATE TABLE [CDN].[KntKarty](
	[Knt_GIDTyp] [smallint] NULL,
	[Knt_GIDFirma] [int] NULL,
	[Knt_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[Knt_GIDLp] [smallint] NULL,
	[Knt_KnATyp] [smallint] NULL,
	[Knt_KnAFirma] [int] NULL,
	[Knt_KnANumer] [int] NULL,
	[Knt_KnALp] [smallint] NULL,
	[Knt_Typ] [tinyint] NULL,
	[Knt_Akwizytor] [smallint] NULL,
	[Knt_Akronim] [varchar](20) NULL,
	[Knt_AkronimFormat] [varchar](30) NULL,
	[Knt_FppKod] [varchar](8) NULL,
	[Knt_Nazwa1] [varchar](50) NULL,
	[Knt_Nazwa2] [varchar](50) NULL,
	[Knt_Nazwa3] [varchar](250) NULL,
	[Knt_KodP] [varchar](10) NULL,
	[Knt_Miasto] [varchar](30) NULL,
	[Knt_Ulica] [varchar](30) NULL,
	[Knt_Adres] [varchar](30) NULL,
	[Knt_NipE] [varchar](20) NULL,
	[Knt_Nip] [varchar](20) NULL,
	[Knt_NipPrefiks] [varchar](2) NULL,
	[Knt_Regon] [varchar](20) NULL,
	[Knt_Pesel] [varchar](11) NULL,
	[Knt_KontoDostawcy] [varchar](50) NULL,
	[Knt_KontoOdbiorcy] [varchar](50) NULL,
	[Knt_Kraj] [varchar](2) NULL,
	[Knt_Powiat] [varchar](30) NULL,
	[Knt_Gmina] [varchar](30) NULL,
	[Knt_Wojewodztwo] [varchar](30) NULL,
	[Knt_RegionCRM] [int] NULL,
	[Knt_GLN] [varchar](13) NULL,
	[Knt_Telefon1] [varchar](30) NULL,
	[Knt_Telefon2] [varchar](30) NULL,
	[Knt_Fax] [varchar](30) NULL,
	[Knt_Modem] [varchar](30) NULL,
	[Knt_Telex] [varchar](30) NULL,
	[Knt_EMail] [varchar](255) NULL,
	[Knt_URL] [varchar](255) NULL,
	[Knt_BnkTyp] [smallint] NULL,
	[Knt_BnkFirma] [int] NULL,
	[Knt_BnkNumer] [int] NULL,
	[Knt_BnkLp] [smallint] NULL,
	[Knt_NrRachunku] [varchar](50) NULL,
	[Knt_Soundex] [varchar](20) NULL,
	[Knt_Rabat] [decimal](5, 2) NULL,
	[Knt_LimitWart] [decimal](15, 2) NULL,
	[Knt_MaxLimitWart] [decimal](15, 2) NULL,
	[Knt_LimitPoTerminie] [decimal](15, 2) NULL,
	[Knt_LimitOkres] [smallint] NULL,
	[Knt_Dewizowe] [tinyint] NULL,
	[Knt_Symbol] [varchar](3) NULL,
	[Knt_NrKursu] [smallint] NULL,
	[Knt_Cena] [smallint] NULL,
	[Knt_FormaPl] [tinyint] NULL,
	[Knt_Marza] [decimal](5, 2) NULL,
	[Knt_TypKarty] [smallint] NULL,
	[Knt_NumerKarty] [varchar](16) NULL,
	[Knt_DataKarty] [int] NULL,
	[Knt_Ean] [varchar](16) NULL,
	[Knt_ObcaKarta] [smallint] NULL,
	[Knt_Osoba] [smallint] NULL,
	[Knt_ExpoKraj] [tinyint] NULL,
	[Knt_SeriaFa] [varchar](5) NULL,
	[Knt_PlatnikVat] [tinyint] NULL,
	[Knt_TypDok] [smallint] NULL,
	[Knt_Status] [tinyint] NULL,
	[Knt_FAVATData] [int] NULL,
	[Knt_SposobDostawy] [varchar](20) NULL,
	[Knt_HasloChk] [varchar](2) NULL,
	[Knt_HasloKontrahent] [varchar](11) NULL,
	[Knt_Dzialalnosc] [tinyint] NULL,
	[Knt_ZTrTyp] [smallint] NULL,
	[Knt_ZTrFirma] [int] NULL,
	[Knt_ZTrNumer] [int] NULL,
	[Knt_ZTrLp] [smallint] NULL,
	[Knt_OpeTyp] [smallint] NULL,
	[Knt_OpeFirma] [int] NULL,
	[Knt_OpeNumer] [int] NULL,
	[Knt_OpeLp] [smallint] NULL,
	[Knt_AkwTyp] [smallint] NULL,
	[Knt_AkwFirma] [int] NULL,
	[Knt_AkwNumer] [int] NULL,
	[Knt_AkwLp] [smallint] NULL,
	[Knt_PrcTyp] [smallint] NULL,
	[Knt_PrcFirma] [int] NULL,
	[Knt_PrcNumer] [int] NULL,
	[Knt_PrcLp] [smallint] NULL,
	[Knt_Atrybut1] [varchar](20) NULL,
	[Knt_Format1] [tinyint] NULL,
	[Knt_Wartosc1] [varchar](255) NULL,
	[Knt_Atrybut2] [varchar](20) NULL,
	[Knt_Format2] [tinyint] NULL,
	[Knt_Wartosc2] [varchar](255) NULL,
	[Knt_Atrybut3] [varchar](20) NULL,
	[Knt_Format3] [tinyint] NULL,
	[Knt_Wartosc3] [varchar](255) NULL,
	[Knt_AkwProwizja] [decimal](7, 4) NULL,
	[Knt_Umowa] [varchar](30) NULL,
	[Knt_DataW] [int] NULL,
	[Knt_LastModL] [int] NULL,
	[Knt_LastModO] [int] NULL,
	[Knt_LastModC] [int] NULL,
	[Knt_FaVATOsw] [varchar](30) NULL,
	[Knt_CechaOpis] [varchar](250) NULL,
	[Knt_Aktywna] [int] NULL,
	[Knt_Wsk] [tinyint] NULL,
	[Knt_OutlookUrl] [varchar](255) NULL,
	[Knt_Nieaktywny] [tinyint] NULL,
	[Knt_Zrodlo] [int] NULL,
	[Knt_Branza] [int] NULL,
	[Knt_Rodzaj] [int] NULL,
	[Knt_RolaPartnera] [int] NULL,
	[Knt_Odleglosc] [decimal](10, 2) NULL,
	[Knt_KarTyp] [smallint] NULL,
	[Knt_KarFirma] [int] NULL,
	[Knt_KarNumer] [int] NULL,
	[Knt_KarLp] [smallint] NULL,
	[Knt_NRB] [smallint] NULL,
	[Knt_Archiwalny] [smallint] NULL,
	[Knt_AdresNieAktualny] [smallint] NULL,
	[Knt_LastTransLockDate] [int] NULL,
	[Knt_OpeTypM] [smallint] NULL,
	[Knt_OpeFirmaM] [int] NULL,
	[Knt_OpeNumerM] [int] NULL,
	[Knt_OpeLpM] [smallint] NULL,
	[Knt_BlokadaTransakcji] [smallint] NULL,
	[Knt_Oddzialowy] [smallint] NULL,
	[Knt_Spedytor] [tinyint] NULL,
	[Knt_TerminPlKa] [int] NULL,
	[Knt_FormaPlKa] [int] NULL,
	[Knt_TerminPlZak] [int] NULL,
	[Knt_FormaPlZak] [int] NULL,
	[Knt_SpTerminPlSpr] [int] NULL,
	[Knt_SpTerminPlRK] [int] NULL,
	[Knt_SpTerminPlZak] [int] NULL,
	[Knt_LimitTerminowy] [smallint] NULL,
	[Knt_DataWygasniecia] [int] NULL,
	[Knt_PIN] [varchar](4) NULL,
	[Knt_Priorytet] [int] NULL,
	[Knt_FrsID] [int] NULL,
	[Knt_Controlling] [tinyint] NULL,
	[Knt_RolnikRyczaltowy] [tinyint] NULL,
	[Knt_PriorytetRez] [tinyint] NULL,
	[Knt_Powiazany] [tinyint] NULL,
	[Knt_PlatnoscKaucji] [tinyint] NULL,
	[Knt_TerminRozliczeniaKaucji] [int] NULL,
	[Knt_KnPTyp] [smallint] NULL,
	[Knt_KnPNumer] [int] NULL,
	[Knt_KnPParam] [tinyint] NULL,
	[Knt_DataUtworzenia] [int] NULL,
	[Knt_DokumentTozsamosci] [varchar](50) NULL,
	[Knt_DataWydania] [int] NULL,
	[Knt_OrganWydajacy] [varchar](50) NULL,
	[Knt_MaxDniPoTerminie] [int] NULL,
	[Knt_KalendarzDst] [int] NULL,
	[Knt_KalendarzWys] [int] NULL,
	[Knt_KnGTyp] [smallint] NULL,
	[Knt_KnGNumer] [int] NULL,
	[Knt_Punkty] [decimal](14, 2) NULL,
	[Knt_KnCTyp] [smallint] NULL,
	[Knt_KnCNumer] [int] NULL,
	[Knt_EFaVatAktywne] [tinyint] NULL,
	[Knt_EFaVatOsw] [varchar](30) NULL,
	[Knt_EFaVatDataDo] [int] NULL,
	[Knt_EFaVatEMail] [varchar](255) NULL,
	[Knt_PodatnikiemNabywca] [tinyint] NULL,
	[Knt_MSTwrGrupaNumer] [int] NULL,
	[Knt_StanPostep] [tinyint] NULL,
	[Knt_ESklep] [tinyint] NULL,
	[Knt_BlokadaZam] [tinyint] NULL,
	[Knt_BlokadaZamTS] [int] NULL,
	[Knt_OpZTyp] [smallint] NULL,
	[Knt_OpZFirma] [int] NULL,
	[Knt_OpZNumer] [int] NULL,
	[Knt_OpZLp] [smallint] NULL,
	[Knt_TypDokZS] [int] NULL,
	[Knt_TypDokZZ] [int] NULL,
	[Knt_PojedynczeDokDoZam] [tinyint] NULL,
	[Knt_MaxTerminPlSpr] [int] NULL,
	[Knt_MaxTerminPlZak] [int] NULL,
	[Knt_DataOdLoj] [int] NULL,
	[Knt_DataDoLoj] [int] NULL,
	[Knt_KartaLoj] [varchar](40) NULL,
	[Knt_PunktyOdebr] [decimal](13, 2) NULL,
	[Knt_PunktyNalicz] [decimal](13, 2) NULL,
	[Knt_PunktyKorekta] [decimal](10, 2) NULL,
	[Knt_PodzialPlat] [tinyint] NULL,
	[Knt_VatWalSys] [tinyint] NULL,
	[Knt_SplitPayment] [tinyint] NULL,
	[Knt_Anonim] [tinyint] NULL,
	[Knt_MetodaKasowa] [tinyint] NULL,
	[Knt_GUID] [varchar](41) NULL,
	[Knt_GUIDdane] [varchar](41) NULL,
	[Knt_DataPromocji] [tinyint] NULL,
	[Knt_VatDataRejestracji] [int] NULL,
	[Knt_VatDataPrzywrocenia] [int] NULL,
	[Knt_VatDataOdmowy] [int] NULL,
	[Knt_VatDataUsuniecia] [int] NULL,
	[Knt_KrajSiedziby] [varchar](2) NULL,
	[Knt_ProcTrnJpk] [varchar](50) NULL,
	[Knt_Kurier] [int] NULL,
	[Knt_OplataSpozZakup] [int] NULL,
	[Knt_OplataSpozSprzedaz] [int] NULL,
	[Knt_WSTO] [tinyint] NULL,
	[Knt_KSeFWyslij] [tinyint] NULL,
	[Knt_AutoZatw] [tinyint] NULL,
	[Knt_KSeFZrodlowy] [tinyint] NULL,
	[Knt_GUIDKarta] [varchar](41) NULL,
	[Knt_CharsetANSI] [tinyint] NULL,
	[Knt_BigApfinoVycWynik] [int] NULL,
	[Knt_BigApfinoVycWynikData] [int] NULL,
	[Knt_BigApfinoVycOczekiwanie] [int] NULL,
	[Knt_AutoWindykacjaApfino] [tinyint] NULL,
  CONSTRAINT [Knt_Primary] PRIMARY KEY CLUSTERED ([Knt_GIDNumer])
)
GO

CREATE TABLE [CDN].[KntLimityK](
	[KLK_Id] [int] IDENTITY(1,1) NOT NULL,
	[KLK_KntTyp] [smallint] NULL,
	[KLK_KntNumer] [int] NULL,
	[KLK_MaxLimitWart] [decimal](15, 2) NULL,
	[KLK_LimitPoTerminie] [decimal](15, 2) NULL,
	[KLK_DataOd] [int] NULL,
	[KLK_DataDo] [int] NULL,
	[KLK_Waluta] [varchar](3) NULL,
	[KLK_NrKursu] [smallint] NULL,
	[KLK_KursM] [decimal](5, 0) NULL,
	[KLK_KursL] [decimal](15, 10) NULL,
	[KLK_PrzeliczajWg] [varchar](20) NULL,
	[KLK_CzasUtworzenia] [int] NULL,
	[KLK_OpeUtworzyl] [int] NULL,
	[KLK_CzasModyfikacji] [int] NULL,
	[KLK_OpeModyfikowal] [int] NULL,
	[KLK_PrzeliczajWgTyp] [tinyint] NULL,
  CONSTRAINT [KLK_Primary] PRIMARY KEY CLUSTERED ([KLK_Id])
)
GO

CREATE TABLE [CDN].[KntOpiekun](
	[KtO_KntTyp] [smallint] NOT NULL,
	[KtO_KntNumer] [int] NOT NULL,
	[KtO_KntLp] [smallint] NOT NULL,
	[KtO_PrcNumer] [int] NOT NULL,
	[KtO_DataOd] [int] NOT NULL,
	[KtO_DataDo] [int] NOT NULL,
	[KtO_Glowny] [tinyint] NULL,
	[KtO_OpeTyp] [smallint] NULL,
	[KtO_OpeFirma] [int] NULL,
	[KtO_OpeNumer] [int] NULL,
	[KtO_OpeLp] [smallint] NULL,
	[KtO_OpeTypM] [smallint] NULL,
	[KtO_OpeFirmaM] [int] NULL,
	[KtO_OpeNumerM] [int] NULL,
	[KtO_OpeLpM] [smallint] NULL,
	[KtO_Uwagi] [varchar](256) NULL,
	[KtO_CzasPrzypisania] [int] NULL,
	[KtO_CzasModyfikacji] [int] NULL,
  CONSTRAINT [KtO_Primary] PRIMARY KEY CLUSTERED ([KtO_KntNumer],[KtO_KntTyp],[KtO_KntLp])
)
GO

CREATE TABLE [CDN].[KntOsoby](
	[KnS_KntTyp] [smallint] NOT NULL,
	[KnS_KntFirma] [int] NULL,
	[KnS_KntNumer] [int] NOT NULL,
	[KnS_KntLp] [smallint] NOT NULL,
	[KnS_Upowazniona] [tinyint] NULL,
	[KnS_UpowaznionaZam] [tinyint] NULL,
	[KnS_Dzial] [varchar](40) NULL,
	[KnS_Stanowisko] [varchar](40) NULL,
	[KnS_Tytul] [varchar](40) NULL,
	[KnS_Nazwa] [varchar](40) NULL,
	[KnS_Telefon] [varchar](30) NULL,
	[KnS_EMail] [varchar](255) NULL,
	[KnS_HasloChk] [varchar](2) NULL,
	[KnS_HasloOsoby] [varchar](11) NULL,
	[KnS_Notatki] [varchar](1024) NULL,
	[KnS_RolaDecyzyjna] [int] NULL,
	[KnS_Fax] [varchar](30) NULL,
	[KnS_TelefonK] [varchar](30) NULL,
	[KnS_UpoDoK] [smallint] NULL,
	[KnS_Archiwalny] [tinyint] NULL,
	[KnS_Pozycja] [smallint] NULL,
	[KnS_CzasModyfikacji] [int] NULL,
	[KnS_AdresId] [int] NULL,
	[KnS_OdpWindykacja] [tinyint] NULL,
	[KnS_Anonim] [tinyint] NULL,
	[KnS_SyncID] [int] IDENTITY(1,1) NOT NULL,
	[KnS_ESklep] [tinyint] NULL,
	[KnS_AdminESklep] [tinyint] NULL,
	[KnS_PreferowanyJezyk] [int] NULL,
	[KnS_GUID] [varchar](40) NULL,
	[KnS_GUID2] [varchar](40) NULL,
	[KnS_CzyEMailUpom] [tinyint] NULL,
	[KnS_CharsetANSI] [tinyint] NULL,
  CONSTRAINT [KnS_Primary] PRIMARY KEY CLUSTERED ([KnS_KntTyp],[KnS_KntNumer],[KnS_KntLp])
)
GO

CREATE TABLE [CDN].[KntPromocje](
	[KPR_Id] [int] IDENTITY(1,1) NOT NULL,
	[KPR_PrmId] [int] NULL,
	[KPR_KntTyp] [smallint] NULL,
	[KPR_KntFirma] [int] NULL,
	[KPR_KntNumer] [int] NULL,
	[KPR_KntLp] [smallint] NULL,
	[KPR_KngTyp] [smallint] NULL,
	[KPR_KngFirma] [int] NULL,
	[KPR_KngNumer] [int] NULL,
	[KPR_KngLp] [smallint] NULL,
	[KPR_Typ] [int] NULL,
	[KPR_Wartosc] [decimal](15, 4) NULL,
	[KPR_OkresTransakcjiOd] [int] NULL,
	[KPR_OkresTransakcjiDo] [int] NULL,
	[KPR_Punkty] [decimal](13, 2) NULL,
	[KPR_GUID] [varchar](41) NULL,
  CONSTRAINT [KPR_Primary] PRIMARY KEY CLUSTERED ([KPR_Id])
) 
GO

CREATE TABLE [CDN].[Magazyny](
	[MAG_GIDTyp] [smallint] NULL,
	[MAG_GIDFirma] [int] NULL,
	[MAG_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[MAG_GIDLp] [smallint] NULL,
	[MAG_Kod] [varchar](10) NULL,
	[MAG_Nazwa] [varchar](30) NULL,
	[MAG_KodP] [varchar](10) NULL,
	[MAG_Miasto] [varchar](30) NULL,
	[MAG_Ulica] [varchar](30) NULL,
	[MAG_Adres] [varchar](30) NULL,
	[MAG_PrcTyp] [smallint] NULL,
	[MAG_PrcFirma] [int] NULL,
	[MAG_PrcNumer] [int] NULL,
	[MAG_PrcLp] [smallint] NULL,
	[MAG_Pojemnosc] [decimal](15, 2) NULL,
	[MAG_Konto] [varchar](50) NULL,
	[MAG_Opis] [varchar](200) NULL,
	[MAG_Wewnetrzny] [tinyint] NULL,
	[MAG_Pico] [tinyint] NULL,
	[MAG_Zarzadzanie] [tinyint] NULL,
	[MAG_KntTyp] [smallint] NULL,
	[MAG_KntFirma] [int] NULL,
	[MAG_KntNumer] [int] NULL,
	[MAG_KntLp] [smallint] NULL,
	[MAG_Zablokowany] [tinyint] NULL,
	[MAG_DataInw] [int] NULL,
	[MAG_KontoInw] [varchar](50) NULL,
	[MAG_Kraj] [varchar](2) NULL,
	[MAG_CzasModyfikacji] [int] NULL,
	[MAG_OpeMNumer] [int] NULL,
	[MAG_AnalizaA] [decimal](5, 2) NULL,
	[MAG_AnalizaB] [decimal](5, 2) NULL,
	[MAG_AnalizaX] [decimal](5, 2) NULL,
	[MAG_AnalizaY] [decimal](5, 2) NULL,
	[MAG_AnalizaABCXYZ] [tinyint] NULL,
	[MAG_WMS] [tinyint] NULL,
	[MAG_SposobPracyZWMS] [smallint] NULL,
	[MAG_RealizujTylkoRezZas] [tinyint] NULL,
	[MAG_WMSNumer] [int] NULL,
	[MAG_WMSRodzaj] [tinyint] NULL,
	[MAG_SposobGenDokMagWMS] [tinyint] NULL,
	[MAG_PcKId] [int] NULL,
	[MAG_RezerwujZasoby] [tinyint] NULL,
	[MAG_KontrolaIlosciWZWM] [tinyint] NULL,
	[MAG_RealizujwPOS] [tinyint] NULL,
  CONSTRAINT [MAG_Primary] PRIMARY KEY CLUSTERED ([MAG_GIDNumer])
)
GO

CREATE TABLE [CDN].[Nazwy](
	[Naz_GIDTyp] [smallint] NOT NULL,
	[Naz_GIDFirma] [int] NULL,
	[Naz_GIDNumer] [int] NULL,
	[Naz_GIDLp] [smallint] NOT NULL,
	[Naz_Nazwa] [varchar](250) NULL,
	[Naz_Nazwa1] [varchar](30) NULL,
	[Naz_Opis] [varchar](60) NULL,
	[Naz_Archiwalny] [tinyint] NULL,
	[Naz_CzasModyfikacji] [int] NULL,
	[Naz_Predefiniowana] [tinyint] NULL,
	[Naz_Nazwa2] [varchar](30) NULL,
  CONSTRAINT [Naz_Primary] PRIMARY KEY CLUSTERED ([Naz_GIDTyp],[Naz_GIDLp])
)
GO

CREATE TABLE [CDN].[PrcKarty](
	[Prc_GIDTyp] [smallint] NULL,
	[Prc_GIDFirma] [int] NULL,
	[Prc_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[Prc_GIDLp] [smallint] NULL,
	[Prc_OpeTyp] [smallint] NULL,
	[Prc_OpeFirma] [int] NULL,
	[Prc_OpeNumer] [int] NULL,
	[Prc_OpeLp] [smallint] NULL,
	[Prc_BnkTyp] [smallint] NULL,
	[Prc_BnkFirma] [int] NULL,
	[Prc_BnkNumer] [int] NULL,
	[Prc_BnkLp] [smallint] NULL,
	[Prc_ZakTyp] [smallint] NULL,
	[Prc_ZakFirma] [int] NULL,
	[Prc_ZakNumer] [int] NULL,
	[Prc_ZakLp] [smallint] NULL,
	[Prc_Akronim] [varchar](20) NULL,
	[Prc_Imie1] [varchar](30) NULL,
	[Prc_Imie2] [varchar](30) NULL,
	[Prc_Nazwisko] [varchar](50) NULL,
	[Prc_KodP] [varchar](10) NULL,
	[Prc_Miasto] [varchar](40) NULL,
	[Prc_Poczta] [varchar](40) NULL,
	[Prc_Ulica] [varchar](30) NULL,
	[Prc_NrDomu] [varchar](10) NULL,
	[Prc_NrLokalu] [varchar](10) NULL,
	[Prc_NipE] [varchar](20) NULL,
	[Prc_Nip] [varchar](20) NULL,
	[Prc_Pesel] [varchar](11) NULL,
	[Prc_EMail] [varchar](255) NULL,
	[Prc_EMail2] [varchar](255) NULL,
	[Prc_Telefon1] [varchar](30) NULL,
	[Prc_TelefonWew1] [varchar](10) NULL,
	[Prc_Telefon2] [varchar](30) NULL,
	[Prc_Telefon3] [varchar](30) NULL,
	[Prc_Telefon4] [varchar](30) NULL,
	[Prc_URL] [varchar](255) NULL,
	[Prc_URL2] [varchar](255) NULL,
	[Prc_NrRachunku] [varchar](50) NULL,
	[Prc_NRB] [tinyint] NULL,
	[Prc_KontoKs1] [varchar](50) NULL,
	[Prc_KontoKs2] [varchar](50) NULL,
	[Prc_KontoKs3] [varchar](50) NULL,
	[Prc_KontoKs4] [varchar](50) NULL,
	[Prc_KontoKs5] [varchar](50) NULL,
	[Prc_FormaNr] [tinyint] NULL,
	[Prc_Ksiegowany] [tinyint] NULL,
	[Prc_Archiwalny] [smallint] NULL,
	[Prc_ArchiwalnyData] [int] NULL,
	[Prc_WmrID] [int] NULL,
	[Prc_TypWymiaru] [tinyint] NULL,
	[Prc_Wyrazenie] [tinyint] NULL,
	[Prc_Inbox] [varchar](2000) NULL,
	[Prc_FrSId] [int] NULL,
	[Prc_OptimaId] [int] NULL,
	[Prc_NTSid] [varchar](100) NULL,
	[Prc_NTKonto] [varchar](255) NULL,
	[Prc_Haslo] [varbinary](16) NULL,
	[Prc_Serwisant] [tinyint] NULL,
	[Prc_PKAId] [int] NULL,
	[Prc_Rodzaj] [int] NULL,
	[Prc_WojStosunek] [tinyint] NULL,
	[Prc_WojWKU] [varchar](50) NULL,
	[Prc_WojNumer] [varchar](20) NULL,
	[Prc_WojPrzydzial] [varchar](30) NULL,
	[Prc_WojStopien] [varchar](30) NULL,
	[Prc_WojSpec] [varchar](30) NULL,
	[Prc_Karany] [tinyint] NULL,
	[Prc_KaranyOpis] [varchar](100) NULL,
	[Prc_ZgodaNaPrzetwarzanie] [tinyint] NULL,
	[Prc_WypadekOsoba] [varchar](50) NULL,
	[Prc_WypadekTelefon] [varchar](30) NULL,
	[Prc_WypadekAdres] [varchar](255) NULL,
	[Prc_Opis] [varchar](500) NULL,
	[Prc_Omnie] [varchar](501) NULL,
	[Prc_MiejscePracy] [varchar](40) NULL,
	[Prc_NrPokoju] [varchar](20) NULL,
	[Prc_PoziomWyksztalcenia] [tinyint] NULL,
	[Prc_OpeWNumer] [int] NULL,
	[Prc_CzasWprowadzenia] [int] NULL,
	[Prc_OpeMNumer] [int] NULL,
	[Prc_CzasModyfikacji] [int] NULL,
	[Prc_ZewnetrznySys] [int] NULL,
	[Prc_DomyslneCentrumKosztId] [int] NULL,
	[Prc_Kraj] [varchar](2) NULL,
	[Prc_ESklep] [tinyint] NULL,
  CONSTRAINT [Prc_Primary] PRIMARY KEY CLUSTERED ([Prc_GIDNumer])
)
GO

CREATE TABLE [CDN].[PrmKarty](
	[PRM_Id] [int] IDENTITY(1,1) NOT NULL,
	[PRM_Akronim] [varchar](200) NULL,
	[PRM_DataOd] [int] NULL,
	[PRM_DataDo] [int] NULL,
	[PRM_Typ] [int] NULL,
	[PRM_Priorytet] [int] NULL,
	[PRM_Stan] [int] NULL,
	[PRM_Aktywna] [int] NULL,
	[PRM_SposobStosowania] [smallint] NULL,
	[PRM_PominPozostale] [smallint] NULL,
	[PRM_Uwagi] [varchar](512) NULL,
	[PRM_Dokument] [smallint] NULL,
	[PRM_LastMod] [int] NULL,
	[PRM_PriorytetLp] [int] NULL,
	[PRM_Cykliczna] [int] NULL,
	[PRM_BlokadaCeny] [tinyint] NULL,
	[PRM_OpeTypM] [smallint] NULL,
	[PRM_OpeFirmaM] [int] NULL,
	[PRM_OpeNumerM] [int] NULL,
	[PRM_OpeLpM] [smallint] NULL,
	[PRM_Pakietowa] [tinyint] NULL,
	[PRM_RodzajPakietu] [tinyint] NULL,
	[PRM_NajwyzszyProg] [tinyint] NULL,
	[PRM_OpeTypU] [smallint] NULL,
	[PRM_OpeNumerU] [int] NULL,
	[PRM_OpeTypP] [smallint] NULL,
	[PRM_OpeNumerP] [int] NULL,
	[PRM_OpeTypZ] [smallint] NULL,
	[PRM_OpeNumerZ] [int] NULL,
	[PRM_DataUtworzenia] [int] NULL,
	[PRM_DataPotwierdzenia] [int] NULL,
	[PRM_DataZamkniecia] [int] NULL,
	[PRM_Kolor] [int] NULL,
	[PRM_KolorBG] [int] NULL,
	[PRM_CyklCzestotliwosc] [smallint] NULL,
	[PRM_CyklRodzaj] [smallint] NULL,
	[PRM_CyklWystepowanie] [int] NULL,
	[PRM_CyklDniOd] [smallint] NULL,
	[PRM_CyklDniDo] [smallint] NULL,
	[PRM_ZamknietaLista] [tinyint] NULL,
	[PRM_LimitTyp] [tinyint] NULL,
	[PRM_LimitWartosc] [decimal](15, 4) NULL,
	[PRM_GrupaTwrWazniejsza] [tinyint] NULL,
	[PRM_ProgTyp] [tinyint] NULL,
	[PRM_ProgWartosc] [decimal](13, 4) NULL,
	[PRM_OkresTransakcjiOd] [int] NULL,
	[PRM_OkresTransakcjiDo] [int] NULL,
	[PRM_WarunekProgSQL] [varchar](2000) NULL,
	[PRM_MaxIloscPakietow] [int] NULL,
	[PRM_LimitRodzaj] [tinyint] NULL,
	[PRM_WymagajJm] [tinyint] NULL,
	[PRM_JmZ] [varchar](8) NULL,
	[PRM_GUID] [varchar](41) NULL,
  CONSTRAINT [PRM_Primary] PRIMARY KEY CLUSTERED ([PRM_Id])
)
GO

CREATE TABLE [CDN].[TwrCeny](
	[TwC_TwrTyp] [smallint] NULL,
	[TwC_TwrFirma] [int] NULL,
	[TwC_TwrNumer] [int] NULL,
	[TwC_TwrLp] [smallint] NULL,
	[TwC_ID] [int] IDENTITY(1,1) NOT NULL,
	[TwC_Waluta] [varchar](3) NULL,
	[TwC_NrKursu] [smallint] NULL,
	[TwC_Marza] [decimal](6, 2) NULL,
	[TwC_Zaok] [decimal](7, 4) NULL,
	[TwC_Offset] [decimal](7, 4) NULL,
	[TwC_RodzajPodstawy] [tinyint] NULL,
	[TwC_Wartosc] [decimal](15, 4) NULL,
	[TwC_Aktualizacja] [tinyint] NULL,
	[TwC_Priorytet] [tinyint] NULL,
	[TwC_CzasModyfikacji] [int] NULL,
	[TwC_KosztyDodatkowe] [decimal](15, 4) NULL,
	[TwC_DokTyp] [smallint] NULL,
	[TwC_DokFirma] [int] NULL,
	[TwC_DokNumer] [int] NULL,
	[TwC_DokLp] [smallint] NULL,
	[TwC_TcnId] [int] NULL,
	[TwC_DataOd] [int] NULL,
	[TwC_KntTyp] [smallint] NULL,
	[TwC_KntFirma] [int] NULL,
	[TwC_KntNumer] [int] NULL,
	[TwC_KntLp] [smallint] NULL,
	[TwC_Aktywny] [int] NULL,
  CONSTRAINT [TwC_Primary] PRIMARY KEY CLUSTERED ([TwC_ID])
)
GO

CREATE TABLE [CDN].[TwrCenyNag](
	[TCN_Id] [int] IDENTITY(1,1) NOT NULL,
	[TCN_RodzajCeny] [int] NULL,
	[TCN_Nazwa] [varchar](100) NULL,
	[TCN_DataOd] [int] NULL,
	[TCN_Stan] [tinyint] NULL,
	[TCN_Aktywny] [int] NULL,
	[TCN_DataUtworzenia] [int] NULL,
	[TCN_OpeWTyp] [smallint] NULL,
	[TCN_OpeWNumer] [int] NULL,
	[TCN_OpeMTyp] [smallint] NULL,
	[TCN_OpeMNumer] [int] NULL,
	[TCN_OpeZTyp] [smallint] NULL,
	[TCN_OpeZNumer] [int] NULL,
	[TCN_TCNId] [int] NULL,
	[TCN_WalutaCenySprzedazy] [varchar](3) NULL,
	[TCN_NrKursu] [smallint] NULL,
	[TCN_Marza] [decimal](6, 2) NULL,
	[TCN_Zaok] [decimal](7, 4) NULL,
	[TCN_Offset] [decimal](7, 4) NULL,
	[TCN_RodzajPodstawy] [tinyint] NULL,
	[TCN_MarzaNarzutOpcja] [tinyint] NULL,
	[TCN_Aktualizacja] [tinyint] NULL,
	[TCN_KntTyp] [smallint] NULL,
	[TCN_KntFirma] [int] NULL,
	[TCN_KntNumer] [int] NULL,
	[TCN_KntLp] [smallint] NULL,
	[TCN_ZmianaProc] [decimal](5, 2) NULL,
	[TCN_Opis] [varchar](255) NULL,
	[TCN_CzasModyfikacji] [int] NULL,
	[TCN_Wsk] [tinyint] NULL,
  CONSTRAINT [TCN_Primary] PRIMARY KEY CLUSTERED ([TCN_Id])
)
GO

CREATE TABLE [CDN].[TwrGrupyDom](
	[TGD_GIDTyp] [smallint] NOT NULL,
	[TGD_GIDFirma] [int] NULL,
	[TGD_GIDNumer] [int] NOT NULL,
	[TGD_GIDLp] [smallint] NULL,
	[TGD_GrOTyp] [smallint] NULL,
	[TGD_GrOFirma] [int] NULL,
	[TGD_GrONumer] [int] NULL,
	[TGD_GrOLp] [smallint] NULL,
	[TGD_Kod] [varchar](40) NULL,
  CONSTRAINT [TGD_Primary] PRIMARY KEY CLUSTERED ([TGD_GIDTyp],[TGD_GIDNumer])
)
GO

CREATE TABLE [CDN].[TwrKarty](
	[Twr_GIDTyp] [smallint] NULL,
	[Twr_GIDFirma] [int] NULL,
	[Twr_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[Twr_GIDLp] [smallint] NULL,
	[Twr_Typ] [tinyint] NULL,
	[Twr_Kod] [varchar](40) NULL,
	[Twr_KodFormat] [varchar](50) NULL,
	[Twr_FPPKod] [varchar](20) NULL,
	[Twr_Nazwa] [varchar](255) NULL,
	[Twr_Nazwa1] [varchar](255) NULL,
	[Twr_Certyfikat] [varchar](60) NULL,
	[Twr_Sww] [varchar](20) NULL,
	[Twr_Ean] [varchar](40) NULL,
	[Twr_Jm] [varchar](8) NULL,
	[Twr_Waga] [decimal](9, 3) NULL,
	[Twr_WJm] [varchar](5) NULL,
	[Twr_JmFormat] [tinyint] NULL,
	[Twr_IloscZam] [decimal](11, 4) NULL,
	[Twr_IloscMin] [decimal](11, 4) NULL,
	[Twr_IloscMax] [decimal](11, 4) NULL,
	[Twr_Ubytek] [decimal](5, 2) NULL,
	[Twr_Prog] [tinyint] NULL,
	[Twr_Upust] [tinyint] NULL,
	[Twr_UpustData] [tinyint] NULL,
	[Twr_UpustDataOd] [int] NULL,
	[Twr_UpustDataDo] [int] NULL,
	[Twr_UpustGodz] [tinyint] NULL,
	[Twr_UpustGodzOd] [int] NULL,
	[Twr_UpustGodzDo] [int] NULL,
	[Twr_AutoZam] [tinyint] NULL,
	[Twr_IloscAZam] [decimal](11, 4) NULL,
	[Twr_CzasDst] [int] NULL,
	[Twr_CenaSpr] [smallint] NULL,
	[Twr_JmDomyslna] [smallint] NULL,
	[Twr_DstDomyslny] [smallint] NULL,
	[Twr_RozliczMag] [tinyint] NULL,
	[Twr_Zakup] [tinyint] NULL,
	[Twr_Sprzedaz] [tinyint] NULL,
	[Twr_GrupaPod] [varchar](1) NULL,
	[Twr_Akcyza] [decimal](5, 2) NULL,
	[Twr_OpeTyp] [smallint] NULL,
	[Twr_OpeFirma] [int] NULL,
	[Twr_OpeNumer] [int] NULL,
	[Twr_OpeLp] [smallint] NULL,
	[Twr_PrcTyp] [smallint] NULL,
	[Twr_PrcFirma] [int] NULL,
	[Twr_PrcNumer] [int] NULL,
	[Twr_PrcLp] [smallint] NULL,
	[Twr_KontaktTyp] [tinyint] NULL,
	[Twr_KontaktZa] [smallint] NULL,
	[Twr_KontaktJC] [tinyint] NULL,
	[Twr_Okresowy] [tinyint] NULL,
	[Twr_Cel] [varchar](200) NULL,
	[Twr_Atrybut1] [varchar](20) NULL,
	[Twr_Format1] [tinyint] NULL,
	[Twr_Wartosc1] [varchar](255) NULL,
	[Twr_Atrybut2] [varchar](20) NULL,
	[Twr_Format2] [tinyint] NULL,
	[Twr_Wartosc2] [varchar](255) NULL,
	[Twr_Atrybut3] [varchar](20) NULL,
	[Twr_Format3] [tinyint] NULL,
	[Twr_Wartosc3] [varchar](255) NULL,
	[Twr_Punkty] [decimal](11, 2) NULL,
	[Twr_Koncesja] [int] NULL,
	[Twr_Konto1] [varchar](50) NULL,
	[Twr_Konto2] [varchar](50) NULL,
	[Twr_Konto3] [varchar](50) NULL,
	[Twr_Polozenie] [varchar](64) NULL,
	[Twr_Katalog] [varchar](40) NULL,
	[Twr_WCenniku] [tinyint] NULL,
	[Twr_EdycjaNazwy] [tinyint] NULL,
	[Twr_BezRabatu] [tinyint] NULL,
	[Twr_KopiujOpis] [tinyint] NULL,
	[Twr_URL] [varchar](255) NULL,
	[Twr_Warunek] [varchar](255) NULL,
	[Twr_ObjetoscL] [decimal](7, 2) NULL,
	[Twr_ObjetoscM] [decimal](5, 0) NULL,
	[Twr_LastModL] [int] NULL,
	[Twr_LastModO] [int] NULL,
	[Twr_LastModC] [int] NULL,
	[Twr_TerminZwrotu] [int] NULL,
	[Twr_ZakupAutoryz] [tinyint] NULL,
	[Twr_MagTyp] [smallint] NULL,
	[Twr_MagFirma] [int] NULL,
	[Twr_MagNumer] [int] NULL,
	[Twr_MagLp] [smallint] NULL,
	[Twr_MarzaMin] [decimal](5, 2) NULL,
	[Twr_KosztUslugi] [decimal](15, 2) NULL,
	[Twr_KosztUTyp] [tinyint] NULL,
	[Twr_CzasWykonania] [int] NULL,
	[Twr_CzasWykonaniaJedn] [tinyint] NULL,
	[Twr_Clo] [decimal](7, 2) NULL,
	[Twr_PodatekImp] [decimal](7, 2) NULL,
	[Twr_StanInfoLimit] [tinyint] NULL,
	[Twr_StanInfoMax] [decimal](15, 4) NULL,
	[Twr_StanInfoProcent] [decimal](3, 0) NULL,
	[Twr_Aktywna] [int] NULL,
	[Twr_Wsk] [tinyint] NULL,
	[Twr_CCKTyp] [smallint] NULL,
	[Twr_CCKFirma] [int] NULL,
	[Twr_CCKNumer] [int] NULL,
	[Twr_CCKLp] [smallint] NULL,
	[Twr_PrdTyp] [smallint] NULL,
	[Twr_PrdFirma] [int] NULL,
	[Twr_PrdNumer] [int] NULL,
	[Twr_PrdLp] [smallint] NULL,
	[Twr_OpeTypM] [smallint] NULL,
	[Twr_OpeFirmaM] [int] NULL,
	[Twr_OpeNumerM] [int] NULL,
	[Twr_OpeLpM] [smallint] NULL,
	[Twr_PCN] [varchar](10) NULL,
	[Twr_Notowania] [int] NULL,
	[Twr_WagaBrutto] [decimal](9, 3) NULL,
	[Twr_WJmBrutto] [varchar](5) NULL,
	[Twr_StawkaPod] [decimal](5, 2) NULL,
	[Twr_FlagaVat] [tinyint] NULL,
	[Twr_Zrodlowa] [decimal](5, 2) NULL,
	[Twr_GrupaPodSpr] [varchar](1) NULL,
	[Twr_StawkaPodSpr] [decimal](5, 2) NULL,
	[Twr_FlagaVatSpr] [tinyint] NULL,
	[Twr_ZrodlowaSpr] [decimal](5, 2) NULL,
	[Twr_Licencja] [smallint] NULL,
	[Twr_Blokada] [smallint] NULL,
	[Twr_Archiwalny] [smallint] NULL,
	[Twr_JMCalkowita] [tinyint] NULL,
	[Twr_Oddzialowy] [smallint] NULL,
	[Twr_JmDomyslnaZak] [smallint] NULL,
	[Twr_KrajPoch] [varchar](2) NULL,
	[Twr_WspFin] [decimal](10, 4) NULL,
	[Twr_PobierzWgCech] [tinyint] NULL,
	[Twr_Kaucja] [tinyint] NULL,
	[Twr_SkNId] [int] NULL,
	[Twr_RejWyposazenia] [tinyint] NULL,
	[Twr_OkresGwarancji] [int] NULL,
	[Twr_GrupaWyposazenia] [int] NULL,
	[Twr_ProdTechnologia] [int] NULL,
	[Twr_ProdAktualnaWersja] [tinyint] NULL,
	[Twr_TwZOdNajwiekszego] [tinyint] NULL,
	[Twr_DataUtworzenia] [int] NULL,
	[Twr_WymJm] [varchar](5) NULL,
	[Twr_PartiaDataW] [tinyint] NULL,
	[Twr_TerminW] [smallint] NULL,
	[Twr_PartiaDostawa] [tinyint] NULL,
	[Twr_NrSeryjnyZCechy] [tinyint] NULL,
	[Twr_ESklep] [tinyint] NULL,
	[Twr_StawkaKGO] [int] NULL,
	[Twr_DostawaEAN] [tinyint] NULL,
	[Twr_MarkaId] [int] NULL,
	[Twr_RejestrujUrzadzenie] [tinyint] NULL,
	[Twr_RodzajUrzadzenia] [int] NULL,
	[Twr_OpisUrzadzenia] [varchar](511) NULL,
	[Twr_KategoriaABCXYZ] [varchar](2) NULL,
	[Twr_RodzajId] [int] NULL,
	[Twr_MobSpr] [tinyint] NULL,
	[Twr_PLM] [tinyint] NULL,
	[Twr_JMBlokujZmiane] [tinyint] NULL,
	[Twr_AnalizaABCXYZ] [tinyint] NULL,
	[Twr_Zlom] [tinyint] NULL,
	[Twr_JMiSklep] [int] NULL,
	[Twr_JMPulpitKnt] [int] NULL,
	[Twr_JMMobSpr] [smallint] NULL,
	[Twr_PIADostepnoscFlaga] [int] NULL,
	[Twr_ObowPodSprId] [int] NULL,
	[Twr_ObowPodZakId] [int] NULL,
	[Twr_RodzajKosztu] [int] NULL,
	[Twr_JMDopelnianiaMobSpr] [smallint] NULL,
	[Twr_Techniczna1] [varchar](255) NULL,
	[Twr_Techniczna2] [varchar](255) NULL,
	[Twr_Techniczna3] [varchar](255) NULL,
	[Twr_Techniczna4] [varchar](255) NULL,
	[Twr_Obcy] [tinyint] NULL,
	[Twr_TechnicznaDec1] [decimal](28, 4) NULL,
	[Twr_MrpId] [int] NULL,
	[Twr_MrpEoq] [decimal](11, 4) NULL,
	[Twr_MrpZaok] [decimal](7, 4) NULL,
	[Twr_AutonumeracjaKod] [varchar](40) NULL,
	[Twr_AutonumeracjaLiczba] [int] NULL,
	[Twr_WysylaniePartiiMobSpr] [tinyint] NULL,
	[Twr_DodEleZez] [tinyint] NULL,
	[Twr_KodOdpadu] [varchar](6) NULL,
	[Twr_MPP] [tinyint] NULL,
	[Twr_GrupaJpk] [varchar](50) NULL,
	[Twr_OplataSpozFlaga] [int] NULL,
	[Twr_StawkaCukierStala] [decimal](7, 2) NULL,
	[Twr_StawkaCukierZmienna] [decimal](7, 2) NULL,
	[Twr_StawkaKofeina] [decimal](7, 2) NULL,
	[Twr_ZawartoscCukru] [decimal](7, 2) NULL,
	[Twr_OplataSpozPrzeliczL] [decimal](15, 0) NULL,
	[Twr_OplataSpozPrzeliczM] [decimal](15, 0) NULL,
	[Twr_OplataSpozDostawyTyp] [tinyint] NULL,
	[Twr_OplataSpozDostawyFlaga] [int] NULL,
	[Twr_OplataSpozNrPartii] [int] NULL,
	[Twr_OplataSpozNrPartiiAtrybut] [int] NULL,
	[Twr_JLogWMS] [tinyint] NULL,
	[Twr_Bon] [tinyint] NULL,
	[Twr_ZPIAId] [int] NULL,
  CONSTRAINT [Twr_Primary] PRIMARY KEY CLUSTERED ([Twr_GIDNumer])
)
GO

CREATE TABLE [CDN].[TwrPromocje](
	[TPR_Id] [int] IDENTITY(1,1) NOT NULL,
	[TPR_PrmId] [int] NULL,
	[TPR_TwrTyp] [smallint] NULL,
	[TPR_TwrFirma] [int] NULL,
	[TPR_TwrNumer] [int] NULL,
	[TPR_TwrLp] [smallint] NULL,
	[TPR_TwgTyp] [smallint] NULL,
	[TPR_TwgFirma] [int] NULL,
	[TPR_TwgNumer] [int] NULL,
	[TPR_TwgLp] [smallint] NULL,
	[TPR_Typ] [int] NULL,
	[TPR_Wartosc] [decimal](15, 4) NULL,
	[TPR_Prog] [decimal](15, 4) NULL,
	[TPR_Waluta] [varchar](3) NULL,
	[TPR_FlagaNB] [varchar](1) NULL,
	[TPR_Notatki] [varchar](200) NULL,
	[TPR_ZstID] [int] NULL,
	[TPR_LP] [int] NULL,
	[TPR_RodzajCeny] [int] NULL,
	[TPR_Wymagany] [tinyint] NULL,
	[TPR_LimitTyp] [tinyint] NULL,
	[TPR_LimitWartosc] [decimal](15, 4) NULL,
	[TPR_ProgTyp] [tinyint] NULL,
	[TPR_ProgWartosc] [decimal](15, 4) NULL,
	[TPR_LimitRodzaj] [tinyint] NULL,
	[TPR_GUID] [varchar](41) NULL,
	[TPR_Aktywny] [tinyint] NULL,
	[TPR_LastMod] [int] NULL,
	[TPR_OpeMod] [varchar](19) NULL,
  CONSTRAINT [TPR_Primary] PRIMARY KEY CLUSTERED ([TPR_Id])
)
GO

CREATE TABLE [CDN].[ZamElem](
	[ZaE_GIDTyp] [smallint] NULL,
	[ZaE_GIDFirma] [int] NULL,
	[ZaE_GIDNumer] [int] NOT NULL,
	[ZaE_GIDLp] [smallint] NOT NULL,
	[ZaE_TwrTyp] [smallint] NULL,
	[ZaE_TwrFirma] [int] NULL,
	[ZaE_TwrNumer] [int] NULL,
	[ZaE_TwrLp] [smallint] NULL,
	[ZaE_TwrNazwa] [varchar](255) NULL,
	[ZaE_TwrKod] [varchar](40) NULL,
	[ZaE_KntTyp] [smallint] NULL,
	[ZaE_KntFirma] [int] NULL,
	[ZaE_KntNumer] [int] NULL,
	[ZaE_KntLp] [smallint] NULL,
	[ZaE_AkwTyp] [smallint] NULL,
	[ZaE_AkwFirma] [int] NULL,
	[ZaE_AkwNumer] [int] NULL,
	[ZaE_AkwLp] [smallint] NULL,
	[ZaE_CChTyp] [smallint] NULL,
	[ZaE_CChFirma] [int] NULL,
	[ZaE_CChNumer] [int] NULL,
	[ZaE_CChLp] [smallint] NULL,
	[ZaE_MagTyp] [smallint] NULL,
	[ZaE_MagFirma] [int] NULL,
	[ZaE_MagNumer] [int] NULL,
	[ZaE_MagLp] [smallint] NULL,
	[ZaE_TStamp] [int] NULL,
	[ZaE_Ilosc] [decimal](11, 4) NULL,
	[ZaE_JmZ] [varchar](8) NULL,
	[ZaE_TypJm] [tinyint] NULL,
	[ZaE_JmFormat] [tinyint] NULL,
	[ZaE_JmFormatZ] [tinyint] NULL,
	[ZaE_PrzeliczM] [decimal](15, 0) NULL,
	[ZaE_PrzeliczL] [decimal](15, 0) NULL,
	[ZaE_GrupaPod] [varchar](1) NULL,
	[ZaE_StawkaPod] [decimal](5, 2) NULL,
	[ZaE_FlagaVAT] [tinyint] NULL,
	[ZaE_Zrodlowa] [decimal](5, 2) NULL,
	[ZaE_Waluta] [varchar](3) NULL,
	[ZaE_NrKursu] [smallint] NULL,
	[ZaE_Rabat] [decimal](5, 2) NULL,
	[ZaE_Cecha] [varchar](255) NULL,
	[ZaE_CenaKatalogowa] [decimal](15, 4) NULL,
	[ZaE_CenaOferowana] [decimal](15, 4) NULL,
	[ZaE_CenaUzgodniona] [decimal](15, 4) NULL,
	[ZaE_RodzajCenyBazowej] [smallint] NULL,
	[ZaE_ProgTyp] [tinyint] NULL,
	[ZaE_Prog] [decimal](15, 2) NULL,
	[ZaE_UpustTyp] [tinyint] NULL,
	[ZaE_Upust] [decimal](15, 2) NULL,
	[ZaE_UpustKntTyp] [tinyint] NULL,
	[ZaE_UpustKnt] [decimal](15, 2) NULL,
	[ZaE_ReETyp] [smallint] NULL,
	[ZaE_ReEFirma] [int] NULL,
	[ZaE_ReENumer] [int] NULL,
	[ZaE_ReELp] [smallint] NULL,
	[ZaE_ReEProdLp] [smallint] NULL,
	[ZaE_DataWaznosciRez] [int] NULL,
	[ZaE_WartoscPoRabacie] [decimal](15, 2) NULL,
	[ZaE_DataPotwDst] [int] NULL,
	[ZaE_DataAktywacjiRez] [int] NULL,
	[ZaE_DataOdZam] [int] NULL,
	[ZaE_PrecyzjaCeny] [tinyint] NULL,
	[ZaE_Rownanie] [tinyint] NULL,
	[ZaE_FlagaNB] [varchar](1) NULL,
	[ZaE_Licencja] [smallint] NULL,
	[ZaE_Pozycja] [smallint] NULL,
	[ZaE_RabatPromocyjny] [decimal](15, 4) NULL,
	[ZaE_RabatKorekta] [decimal](15, 4) NULL,
	[ZaE_Promocje] [int] NULL,
	[ZaE_ZstTyp] [smallint] NULL,
	[ZaE_ZstFirma] [int] NULL,
	[ZaE_ZstNumer] [int] NULL,
	[ZaE_ZstLp] [smallint] NULL,
	[ZaE_PrecyzjaCenyPocz] [smallint] NULL,
	[ZaE_CenaSpr] [smallint] NULL,
	[ZaE_RodzajDatyRealizacji] [smallint] NULL,
	[ZaE_KGOJednostkowe] [decimal](9, 2) NULL,
	[ZaE_OddElemId] [int] NULL,
	[ZaE_IloscMin] [decimal](11, 4) NULL,
	[ZaE_IloscMax] [decimal](11, 4) NULL,
	[ZaE_PakietId] [int] NULL,
	[ZaE_Gratis] [smallint] NULL,
	[ZaE_PromocjaProgID] [int] NULL,
	[ZaE_Zlom] [smallint] NULL,
	[ZaE_FormatkaCyr] [tinyint] NULL,
	[ZaE_KPNId] [int] NULL,
	[ZaE_TypCenyNabycia] [tinyint] NULL,
	[ZaE_PakietWymaganaPoz] [tinyint] NULL,
	[ZaE_PakietTwgNumer] [int] NULL,
	[ZaE_PakietTwgTyp] [smallint] NULL,
	[ZaE_RabatOpeGen] [decimal](15, 2) NULL,
	[ZaE_WymuszonePRMID] [int] NULL,
	[ZaE_Punkty] [decimal](11, 2) NULL,
	[ZaE_Nagroda] [smallint] NULL,
	[ZaE_ReNNumer] [int] NULL,
	[ZaE_OplataSpozFlaga] [tinyint] NULL,
	[ZaE_StawkaCukierStala] [decimal](7, 2) NULL,
	[ZaE_StawkaCukierZmienna] [decimal](7, 2) NULL,
	[ZaE_StawkaKofeina] [decimal](7, 2) NULL,
	[ZaE_JmDzielWZWM] [tinyint] NULL,
	[ZaE_GUID] [varchar](36) NULL,
  CONSTRAINT [ZaE_Primary] PRIMARY KEY CLUSTERED ([ZaE_GIDNumer],[ZaE_GIDLp])
)
GO

CREATE TABLE [CDN].[ZamNag](
	[ZaN_GIDTyp] [smallint] NULL,
	[ZaN_GIDFirma] [int] NULL,
	[ZaN_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[ZaN_GIDLp] [smallint] NULL,
	[ZaN_ZrdTyp] [smallint] NULL,
	[ZaN_ZrdFirma] [int] NULL,
	[ZaN_ZrdNumer] [int] NULL,
	[ZaN_ZrdLp] [smallint] NULL,
	[ZaN_KorTyp] [smallint] NULL,
	[ZaN_KorFirma] [int] NULL,
	[ZaN_KorNumer] [int] NULL,
	[ZaN_KorLp] [smallint] NULL,
	[ZaN_KntTyp] [smallint] NULL,
	[ZaN_KntFirma] [int] NULL,
	[ZaN_KntNumer] [int] NULL,
	[ZaN_KntLp] [smallint] NULL,
	[ZaN_KnATyp] [smallint] NULL,
	[ZaN_KnAFirma] [int] NULL,
	[ZaN_KnANumer] [int] NULL,
	[ZaN_KnALp] [smallint] NULL,
	[ZaN_AkwTyp] [smallint] NULL,
	[ZaN_AkwFirma] [int] NULL,
	[ZaN_AkwNumer] [int] NULL,
	[ZaN_AkwLp] [smallint] NULL,
	[ZaN_AdWTyp] [smallint] NULL,
	[ZaN_AdwFirma] [int] NULL,
	[ZaN_AdWNumer] [int] NULL,
	[ZaN_AdWLp] [smallint] NULL,
	[ZaN_MagTyp] [smallint] NULL,
	[ZaN_MagFirma] [int] NULL,
	[ZaN_MagNumer] [int] NULL,
	[ZaN_MagLp] [smallint] NULL,
	[ZaN_FormaNr] [tinyint] NULL,
	[ZaN_FormaNazwa] [varchar](15) NULL,
	[ZaN_FormaRabat] [decimal](5, 2) NULL,
	[ZaN_TerminPlatnosci] [int] NULL,
	[ZaN_ZamTyp] [smallint] NULL,
	[ZaN_ZamRok] [smallint] NULL,
	[ZaN_ZamMiesiac] [tinyint] NULL,
	[ZaN_ZamSeria] [varchar](5) NULL,
	[ZaN_ZamNumer] [int] NULL,
	[ZaN_ZamLp] [smallint] NULL,
	[ZaN_PomTyp] [smallint] NULL,
	[ZaN_PomRok] [smallint] NULL,
	[ZaN_PomMiesiac] [tinyint] NULL,
	[ZaN_PomSeria] [varchar](5) NULL,
	[ZaN_PomNumer] [int] NULL,
	[ZaN_PomLp] [smallint] NULL,
	[ZaN_DokumentObcy] [varchar](40) NULL,
	[ZaN_DokumentObcyCharset] [int] NULL,
	[ZaN_DokumentObcyP] [varchar](40) NULL,
	[ZaN_DokumentObcyPCharset] [int] NULL,
	[ZaN_ExpoNorm] [tinyint] NULL,
	[ZaN_Waluta] [varchar](3) NULL,
	[ZaN_NrKursu] [smallint] NULL,
	[ZaN_KursM] [decimal](5, 0) NULL,
	[ZaN_KursL] [decimal](15, 10) NULL,
	[ZaN_TypKursu] [tinyint] NULL,
	[ZaN_WspolnaWaluta] [tinyint] NOT NULL,
	[ZaN_OpeTypW] [smallint] NULL,
	[ZaN_OpeFirmaW] [int] NULL,
	[ZaN_OpeNumerW] [int] NULL,
	[ZaN_OpeLpW] [smallint] NULL,
	[ZaN_OpeTypM] [smallint] NULL,
	[ZaN_OpeFirmaM] [int] NULL,
	[ZaN_OpeNumerM] [int] NULL,
	[ZaN_OpeLpM] [smallint] NULL,
	[ZaN_OpeTypZ] [smallint] NULL,
	[ZaN_OpeFirmaZ] [int] NULL,
	[ZaN_OpeNumerZ] [int] NULL,
	[ZaN_OpeLpZ] [smallint] NULL,
	[ZaN_OpeTypP] [smallint] NULL,
	[ZaN_OpeFirmaP] [int] NULL,
	[ZaN_OpeNumerP] [int] NULL,
	[ZaN_OpeLpP] [smallint] NULL,
	[ZaN_ID] [int] NULL,
	[ZaN_Rabat] [decimal](15, 2) NULL,
	[ZaN_TypRabatu] [tinyint] NULL,
	[ZaN_SpDostawy] [varchar](20) NULL,
	[ZaN_CechaOpis] [varchar](250) NULL,
	[ZaN_DataZapytania] [int] NULL,
	[ZaN_RealWCalosci] [tinyint] NULL,
	[ZaN_DataWystawienia] [int] NULL,
	[ZaN_DataRealizacji] [int] NULL,
	[ZaN_DataWaznosci] [int] NULL,
	[ZaN_DataPotwierdz] [int] NULL,
	[ZaN_DataAkceptacji] [int] NULL,
	[ZaN_DataOdZam] [int] NULL,
	[ZaN_Stan] [smallint] NULL,
	[ZaN_Aktywny] [int] NULL,
	[ZaN_DokZwiazane] [tinyint] NULL,
	[ZaN_LKopii] [tinyint] NULL,
	[ZaN_Wsk] [tinyint] NULL,
	[ZaN_KnSTyp] [smallint] NULL,
	[ZaN_KnSFirma] [int] NULL,
	[ZaN_KnSNumer] [int] NULL,
	[ZaN_KnSLp] [smallint] NULL,
	[ZaN_KnSTypP] [smallint] NULL,
	[ZaN_KnSFirmaP] [int] NULL,
	[ZaN_KnSNumerP] [int] NULL,
	[ZaN_KnSLpP] [smallint] NULL,
	[ZaN_Rodzaj] [smallint] NULL,
	[ZaN_PcKID] [int] NULL,
	[ZaN_KnDTyp] [smallint] NULL,
	[ZaN_KnDFirma] [int] NULL,
	[ZaN_KnDNumer] [int] NULL,
	[ZaN_KnDLp] [smallint] NULL,
	[ZaN_FiaskoID] [smallint] NULL,
	[ZaN_RokMiesiac] [int] NULL,
	[ZaN_PotwOferty] [smallint] NULL,
	[ZaN_DataPotwOferty] [int] NULL,
	[ZaN_OpeTypPotwOfe] [smallint] NULL,
	[ZaN_OpeFirmaPotwOfe] [int] NULL,
	[ZaN_OpeNumerPotwOfe] [int] NULL,
	[ZaN_OpeLpPotwOfe] [smallint] NULL,
	[ZaN_DataAktywacjiRez] [int] NULL,
	[ZaN_Url] [varchar](255) NULL,
	[ZaN_RabatW] [decimal](15, 2) NULL,
	[ZaN_FrSID] [int] NULL,
	[ZaN_FlagaNB] [varchar](1) NULL,
	[ZaN_OpeTypMod] [smallint] NULL,
	[ZaN_OpeFirmaMod] [int] NULL,
	[ZaN_OpeNumerMod] [int] NULL,
	[ZaN_OpeLpMod] [smallint] NULL,
	[ZaN_OddDokId] [int] NULL,
	[ZaN_LastMod] [int] NULL,
	[ZaN_OpiTyp] [smallint] NULL,
	[ZaN_OpiFirma] [int] NULL,
	[ZaN_OpiNumer] [int] NULL,
	[ZaN_OpiLP] [smallint] NULL,
	[ZaN_IncotermsSymbol] [varchar](4) NULL,
	[ZaN_IncotermsMiejsce] [varchar](255) NULL,
	[ZaN_KrajPrzezWys] [varchar](2) NULL,
	[ZaN_KodRodzajuTransportu] [varchar](2) NULL,
	[ZaN_KodRodzajuTransakcji] [varchar](2) NULL,
	[ZaN_Wyslano] [tinyint] NULL,
	[ZaN_CenaSpr] [smallint] NULL,
	[ZaN_GodzinaWystawienia] [int] NULL,
	[ZaN_GodzinaPotwierdzenia] [int] NULL,
	[ZaN_Promocje] [int] NULL,
	[ZaN_RezerwujZasoby] [tinyint] NULL,
	[ZaN_PriorytetRez] [tinyint] NULL,
	[ZaN_RabatPromocyjnyGlobalny] [decimal](15, 4) NULL,
	[ZaN_KnPTyp] [smallint] NULL,
	[ZaN_KnPNumer] [int] NULL,
	[ZaN_AdPNumer] [int] NULL,
	[ZaN_MaGDTyp] [smallint] NULL,
	[ZaN_MagDNumer] [int] NULL,
	[ZaN_KarNumer] [int] NULL,
	[ZaN_PrjId] [int] NULL,
	[ZaN_KnSTypOdb] [smallint] NULL,
	[ZaN_KnSFirmaOdb] [int] NULL,
	[ZaN_KnSNumerOdb] [int] NULL,
	[ZaN_KnSLpOdb] [smallint] NULL,
	[ZaN_KnSTypPlt] [smallint] NULL,
	[ZaN_KnSFirmaPlt] [int] NULL,
	[ZaN_KnSNumerPlt] [int] NULL,
	[ZaN_KnSLpPlt] [smallint] NULL,
	[ZaN_RodzajDatyRealizacji] [tinyint] NULL,
	[ZaN_FrMNumer] [int] NULL,
	[ZaN_PromocjePar] [tinyint] NULL,
	[ZaN_RezerwacjeNaNiepotwierdzonym] [tinyint] NULL,
	[ZaN_StanZapytania] [smallint] NULL,
	[ZaN_OpeNumerPotwZapyt] [int] NULL,
	[ZaN_GenerujWieleZam] [tinyint] NULL,
	[ZaN_FormatkaCyr] [tinyint] NULL,
	[ZaN_WtrID] [int] NULL,
	[ZaN_WtrProgID] [int] NULL,
	[ZaN_DomyslnyDokRealizacja] [smallint] NULL,
	[ZaN_DataPromocjiRodzaj] [tinyint] NULL,
	[ZaN_RezZasTylkoAktywne] [tinyint] NULL,
	[ZaN_PrzyczynaZW] [varchar](255) NULL,
	[ZaN_PodstawaZW] [tinyint] NULL,
	[ZaN_LimitKredytowy] [tinyint] NULL,
	[ZaN_LimitKredytowyKwota] [decimal](15, 2) NULL,
	[ZaN_LimitKredytowyWaznyDo] [int] NULL,
	[ZaN_LimitKredytowyWaluta] [varchar](3) NULL,
	[ZaN_KontrolujIlosciPrzyGenZam] [tinyint] NULL,
	[ZaN_OplataSpozFlaga] [tinyint] NULL,
	[ZaN_GUID] [varchar](36) NULL,
	[ZaN_OperatorPOS] [int] NULL,
	[ZaN_OstatniaModyfikacjaPOS] [int] NULL,
	[ZaN_ZrodloPochodzeniaESklep] [int] NULL,
	[ZaN_StatusPlatnosciPOS] [int] NULL,
	[ZaN_StatusRealizacji] [int] NULL,
	[ZaN_EAN] [varchar](50) NULL,
	[ZaN_PsAID] [int] NULL,
  CONSTRAINT [ZaN_Primary] PRIMARY KEY CLUSTERED ([ZaN_GIDNumer])
)
GO

CREATE TABLE [CDN].[TwrZasoby](
	[TwZ_DstTyp] [smallint] NULL,
	[TwZ_DstFirma] [int] NULL,
	[TwZ_DstNumer] [int] NOT NULL,
	[TwZ_DstLp] [smallint] NULL,
	[TwZ_TwrTyp] [smallint] NULL,
	[TwZ_TwrFirma] [int] NULL,
	[TwZ_TwrNumer] [int] NULL,
	[TwZ_TwrLp] [smallint] NULL,
	[TwZ_MagTyp] [smallint] NULL,
	[TwZ_MagFirma] [int] NULL,
	[TwZ_MagNumer] [int] NOT NULL,
	[TwZ_MagLp] [smallint] NULL,
	[TwZ_DataP] [int] NULL,
	[TwZ_KsiegowaNetto] [decimal](15, 2) NULL,
	[TwZ_RzeczywistaNetto] [decimal](15, 2) NULL,
	[TwZ_Ean] [varchar](40) NULL,
	[TwZ_Polozenie] [varchar](64) NULL,
	[TwZ_DataW] [int] NULL,
	[TwZ_KosztKsiegowy] [decimal](15, 2) NULL,
	[TwZ_KosztRzeczywisty] [decimal](15, 2) NULL,
	[TwZ_IlSpr] [decimal](15, 4) NULL,
	[TwZ_IlMag] [decimal](15, 4) NULL,
	[TwZ_Ilosc] [decimal](15, 4) NULL,
	[TwZ_IloscWMS] [decimal](15, 4) NULL,
  CONSTRAINT [TwZ_Primary] PRIMARY KEY CLUSTERED ([TwZ_DstNumer], [TwZ_MagNumer])
)
GO

CREATE TABLE [CDN].[BilansOtwarciaElem](
	[BOE_GIDTyp] [smallint] NOT NULL,
	[BOE_GIDFirma] [int] NULL,
	[BOE_GIDNumer] [int] NOT NULL,
	[BOE_GIDLp] [smallint] NOT NULL,
	[BOE_Status] [tinyint] NULL,
	[BOE_Konto] [varchar](50) NULL,
	[BOE_KwotaDebet] [decimal](15, 2) NULL,
	[BOE_KwotaBODebet] [decimal](15, 2) NULL,
	[BOE_KwotaCredit] [decimal](15, 2) NULL,
	[BOE_KwotaBOCredit] [decimal](15, 2) NULL,
	[BOE_Opis] [varchar](255) NULL,
	[BOE_KntTyp] [smallint] NULL,
	[BOE_KntNumer] [int] NULL,
  CONSTRAINT [BOE_Primary] PRIMARY KEY CLUSTERED ([BOE_GIDTyp],[BOE_GIDNumer],[BOE_GIDLp])
)
GO

CREATE TABLE [CDN].[BilansOtwarciaSElem](
	[BOS_GIDTyp] [smallint] NOT NULL,
	[BOS_GIDFirma] [int] NULL,
	[BOS_GIDNumer] [int] NOT NULL,
	[BOS_GIDLp] [smallint] NOT NULL,
	[BOS_SubGIDLp] [smallint] NOT NULL,
	[BOS_Data] [int] NULL,
	[BOS_Termin] [int] NULL,
	[BOS_NumerDokumentu] [varchar](40) NULL,
	[BOS_DC] [tinyint] NULL,
	[BOS_Kwota] [decimal](15, 2) NULL,
	[BOS_KwotaBO] [decimal](15, 2) NULL,
	[BOS_Waluta] [varchar](3) NULL,
	[BOS_NrKursu] [smallint] NULL,
	[BOS_KursL] [decimal](15, 10) NULL,
	[BOS_KursM] [decimal](5, 0) NULL,
	[BOS_KwotaWal] [decimal](15, 2) NULL,
	[BOS_KwotaBOWal] [decimal](15, 2) NULL,
	[BOS_TRPTyp] [smallint] NULL,
	[BOS_TRPFirma] [int] NULL,
	[BOS_TRPNumer] [int] NULL,
	[BOS_TRPLp] [smallint] NULL,
	[BOS_DZKTyp] [smallint] NULL,
	[BOS_DZKFirma] [int] NULL,
	[BOS_DZKNumer] [int] NULL,
	[BOS_DZKLp] [smallint] NULL,
 CONSTRAINT [BOS_Primary] PRIMARY KEY CLUSTERED ([BOS_GIDTyp],[BOS_GIDNumer],[BOS_GIDLp],[BOS_SubGIDLp])
)
GO

CREATE TABLE [CDN].[Obiekty](
	[OB_GIDTyp] [smallint] NOT NULL,
	[OB_Skrot] [varchar](5) NULL,
	[OB_Nazwa] [varchar](40) NULL,
	[OB_Opis] [varchar](256) NULL,
 CONSTRAINT [OB_Primary] PRIMARY KEY CLUSTERED ([OB_GIDTyp])
)
GO

CREATE TABLE [CDN].[TraElem](
	[TrE_GIDTyp] [smallint] NULL,
	[TrE_GIDFirma] [int] NULL,
	[TrE_GIDNumer] [int] NOT NULL,
	[TrE_GIDLp] [smallint] NOT NULL,
	[TrE_Pozycja] [smallint] NULL,
	[TrE_TwrTyp] [smallint] NULL,
	[TrE_TwrFirma] [int] NULL,
	[TrE_TwrNumer] [int] NULL,
	[TrE_TwrLp] [smallint] NULL,
	[TrE_TwrNazwa] [varchar](255) NULL,
	[TrE_TwrKod] [varchar](40) NULL,
	[TrE_TypTwr] [tinyint] NULL,
	[TrE_KntTyp] [smallint] NULL,
	[TrE_KntFirma] [int] NULL,
	[TrE_KntNumer] [int] NULL,
	[TrE_KntLp] [smallint] NULL,
	[TrE_AkwTyp] [smallint] NULL,
	[TrE_AkwFirma] [int] NULL,
	[TrE_AkwNumer] [int] NULL,
	[TrE_AkwLp] [smallint] NULL,
	[TrE_TrnTStamp] [int] NULL,
	[TrE_Punkty] [decimal](11, 2) NULL,
	[TrE_Ilosc] [decimal](11, 4) NULL,
	[TrE_JmFormat] [tinyint] NULL,
	[TrE_JmZ] [varchar](8) NULL,
	[TrE_JmFormatZ] [tinyint] NULL,
	[TrE_TypJm] [tinyint] NULL,
	[TrE_PrzeliczM] [decimal](15, 0) NULL,
	[TrE_PrzeliczL] [decimal](15, 0) NULL,
	[TrE_GrupaPod] [varchar](1) NULL,
	[TrE_StawkaPod] [decimal](5, 2) NULL,
	[TrE_FlagaVat] [tinyint] NULL,
	[TrE_Zrodlowa] [decimal](5, 2) NULL,
	[TrE_Akcyza] [decimal](5, 2) NULL,
	[TrE_Waluta] [varchar](3) NULL,
	[TrE_NrKursu] [smallint] NULL,
	[TrE_KursM] [decimal](5, 0) NULL,
	[TrE_KursL] [decimal](15, 10) NULL,
	[TrE_Poczatkowa] [decimal](15, 4) NULL,
	[TrE_FlagaNB] [varchar](1) NULL,
	[TrE_Rabat] [decimal](5, 2) NULL,
	[TrE_WartoscPoRabacie] [decimal](15, 2) NULL,
	[TrE_KsiegowaNetto] [decimal](15, 2) NULL,
	[TrE_KsiegowaBrutto] [decimal](15, 2) NULL,
	[TrE_RzeczywistaNetto] [decimal](15, 2) NULL,
	[TrE_KosztKsiegowy] [decimal](15, 2) NULL,
	[TrE_KosztRzeczywisty] [decimal](15, 2) NULL,
	[TrE_ProgTyp] [tinyint] NULL,
	[TrE_Prog] [decimal](15, 2) NULL,
	[TrE_UpustTyp] [tinyint] NULL,
	[TrE_Upust] [decimal](15, 2) NULL,
	[TrE_UpustKnt] [decimal](15, 4) NULL,
	[TrE_UpustKntTyp] [tinyint] NULL,
	[TrE_IloscDPPrzed] [decimal](11, 4) NULL,
	[TrE_KsiegowyDPPrzed] [decimal](15, 2) NULL,
	[TrE_ZlcTyp] [smallint] NULL,
	[TrE_ZlcFirma] [int] NULL,
	[TrE_ZlcNumer] [int] NULL,
	[TrE_ZlcLp] [smallint] NULL,
	[TrE_RecTyp] [smallint] NULL,
	[TrE_RecFirma] [int] NULL,
	[TrE_RecNumer] [int] NULL,
	[TrE_RecLp] [smallint] NULL,
	[TrE_Cena] [decimal](15, 4) NULL,
	[TrE_Rownanie] [tinyint] NULL,
	[TrE_OdKsiegowych] [tinyint] NULL,
	[TrE_RzeczywistyDPPrzed] [decimal](15, 2) NULL,
	[TrE_PCN] [varchar](10) NULL,
	[TrE_PrecyzjaCeny] [tinyint] NULL,
	[TrE_VatTyp] [smallint] NULL,
	[TrE_VatFirma] [int] NULL,
	[TrE_VatNumer] [int] NULL,
	[TrE_VatLp] [smallint] NULL,
	[TrE_KosztVat] [tinyint] NULL,
	[TrE_KosztNetto] [tinyint] NULL,
	[TrE_Licencja] [smallint] NULL,
	[TrE_KrajPoch] [varchar](2) NULL,
	[TrE_RabatPromocyjny] [decimal](15, 4) NULL,
	[TrE_RabatKorekta] [decimal](15, 4) NULL,
	[TrE_Promocje] [int] NULL,
	[TrE_ZstTyp] [smallint] NULL,
	[TrE_ZstFirma] [int] NULL,
	[TrE_ZstNumer] [int] NULL,
	[TrE_ZstLp] [smallint] NULL,
	[TrE_PrecyzjaCenyPocz] [tinyint] NULL,
	[TrE_ZwroconoCalaIlosc] [tinyint] NULL,
	[TrE_RodzajCenyBazowej] [smallint] NULL,
	[TrE_KosztBazowy] [decimal](15, 2) NULL,
	[TrE_WartoscBazowa] [decimal](15, 2) NULL,
	[TrE_CenaSpr] [smallint] NULL,
	[TrE_CenaPoRabacie] [decimal](15, 4) NULL,
	[TrE_CChTyp] [smallint] NULL,
	[TrE_CChNumer] [int] NULL,
	[TrE_Cecha] [varchar](255) NULL,
	[TrE_KGOJednostkowe] [decimal](9, 2) NULL,
	[TrE_IloscMin] [decimal](11, 4) NULL,
	[TrE_IloscMax] [decimal](11, 4) NULL,
	[TrE_PakietId] [int] NULL,
	[TrE_Gratis] [smallint] NULL,
	[TrE_PromocjaProgID] [int] NULL,
	[TrE_FormatkaCyr] [tinyint] NULL,
	[TrE_Zlom] [smallint] NULL,
	[TrE_IloscPrzedKorekta] [decimal](11, 4) NULL,
	[TrE_CenaPrzedKorekta] [decimal](15, 4) NULL,
	[TrE_WartoscPrzedKorekta] [decimal](15, 2) NULL,
	[TrE_GrupaPodPrzedKorekta] [varchar](1) NULL,
	[TrE_StawkaPodPrzedKorekta] [decimal](5, 2) NULL,
	[TrE_FlagaVatPrzedKorekta] [tinyint] NULL,
	[TrE_ZrodlowaPrzedKorekta] [decimal](5, 2) NULL,
	[TrE_AkcyzaPrzedKorekta] [decimal](5, 2) NULL,
	[TrE_PrzyczynaKorekty] [varchar](255) NULL,
	[TrE_KatDatyOP] [tinyint] NULL,
	[TrE_RodzajKosztu] [int] NULL,
	[TrE_PakietTwgNumer] [int] NULL,
	[TrE_PakietTwgTyp] [smallint] NULL,
	[TrE_RabatOpeGen] [decimal](15, 2) NULL,
	[TrE_PakietWymaganaPoz] [tinyint] NULL,
	[TrE_SentId] [int] NULL,
	[TrE_Nagroda] [smallint] NULL,
	[TrE_OperatorPOS] [int] NULL,
	[TrE_SentElemId] [int] NULL,
	[TrE_GUID] [varchar](40) NULL,
	[TrE_OplataSpozFlaga] [tinyint] NULL,
	[TrE_StawkaCukierStala] [decimal](7, 2) NULL,
	[TrE_StawkaCukierZmienna] [decimal](7, 2) NULL,
	[TrE_StawkaKofeina] [decimal](7, 2) NULL,
	[TrE_Bon] [tinyint] NULL,
 CONSTRAINT [TrE_Primary] PRIMARY KEY CLUSTERED ([TrE_GIDNumer],[TrE_GIDLp])
)
GO

CREATE TABLE [CDN].[TraNag](
	[TrN_GIDTyp] [smallint] NULL,
	[TrN_GIDFirma] [int] NULL,
	[TrN_GIDNumer] [int] IDENTITY(1,1) NOT NULL,
	[TrN_GIDLp] [smallint] NULL,
	[TrN_ZwrTyp] [smallint] NULL,
	[TrN_ZwrFirma] [int] NULL,
	[TrN_ZwrNumer] [int] NULL,
	[TrN_ZwrLp] [smallint] NULL,
	[TrN_SpiTyp] [smallint] NULL,
	[TrN_SpiFirma] [int] NULL,
	[TrN_SpiNumer] [int] NULL,
	[TrN_SpiLp] [smallint] NULL,
	[TrN_RelTyp] [smallint] NULL,
	[TrN_RelFirma] [int] NULL,
	[TrN_RelNumer] [int] NULL,
	[TrN_RelLp] [smallint] NULL,
	[TrN_KntTyp] [smallint] NULL,
	[TrN_KntFirma] [int] NULL,
	[TrN_KntNumer] [int] NULL,
	[TrN_KntLp] [smallint] NULL,
	[TrN_KnATyp] [smallint] NULL,
	[TrN_KnAFirma] [int] NULL,
	[TrN_KnANumer] [int] NULL,
	[TrN_KnALp] [smallint] NULL,
	[TrN_AkwTyp] [smallint] NULL,
	[TrN_AkwFirma] [int] NULL,
	[TrN_AkwNumer] [int] NULL,
	[TrN_AkwLp] [smallint] NULL,
	[TrN_AdWTyp] [smallint] NULL,
	[TrN_AdWFirma] [int] NULL,
	[TrN_AdWNumer] [int] NULL,
	[TrN_AdWLp] [smallint] NULL,
	[TrN_SchTyp] [smallint] NULL,
	[TrN_SchFirma] [int] NULL,
	[TrN_SchNumer] [int] NULL,
	[TrN_SchLp] [smallint] NULL,
	[TrN_ZaNTyp] [smallint] NULL,
	[TrN_ZaNFirma] [int] NULL,
	[TrN_ZaNNumer] [int] NULL,
	[TrN_ZaNLp] [smallint] NULL,
	[TrN_SaNTyp] [smallint] NULL,
	[TrN_SaNFirma] [int] NULL,
	[TrN_SaNNumer] [int] NULL,
	[TrN_SaNLp] [smallint] NULL,
	[TrN_KonTyp] [smallint] NULL,
	[TrN_KonFirma] [int] NULL,
	[TrN_KonNumer] [int] NULL,
	[TrN_KonLp] [smallint] NULL,
	[TrN_TKTyp] [smallint] NULL,
	[TrN_TKFirma] [int] NULL,
	[TrN_TKNumer] [int] NULL,
	[TrN_TKLp] [smallint] NULL,
	[TrN_Dziennik] [varchar](5) NULL,
	[TrN_Data2] [int] NULL,
	[TrN_Data3] [int] NULL,
	[TrN_TrNTyp] [smallint] NULL,
	[TrN_TrNRok] [smallint] NULL,
	[TrN_TrNMiesiac] [tinyint] NULL,
	[TrN_TrNSeria] [varchar](5) NULL,
	[TrN_TrNNumer] [int] NULL,
	[TrN_TrNLp] [smallint] NULL,
	[TrN_VatTyp] [smallint] NULL,
	[TrN_VatRejestr] [varchar](5) NULL,
	[TrN_VatRok] [smallint] NULL,
	[TrN_VatMiesiac] [smallint] NULL,
	[TrN_VatDzien] [smallint] NULL,
	[TrN_VatNumer] [int] NULL,
	[TrN_VatKorekta] [tinyint] NULL,
	[TrN_DeklRok] [smallint] NULL,
	[TrN_DeklMiesiac] [smallint] NULL,
	[TrN_Rozliczac] [tinyint] NULL,
	[TrN_DokumentObcy] [varchar](40) NULL,
	[TrN_DokumentObcyCharset] [int] NULL,
	[TrN_ZamDokumentObcy] [varchar](40) NULL,
	[TrN_NrKorekty] [varchar](40) NULL,
	[TrN_OdliczeniaVat] [tinyint] NULL,
	[TrN_RodzajZakupu] [tinyint] NULL,
	[TrN_ExpoNorm] [tinyint] NULL,
	[TrN_Detal] [tinyint] NULL,
	[TrN_FlagaNB] [varchar](1) NULL,
	[TrN_CenaSpr] [smallint] NULL,
	[TrN_Fiskalny] [tinyint] NULL,
	[TrN_FormaNr] [tinyint] NULL,
	[TrN_FormaNazwa] [varchar](15) NULL,
	[TrN_FormaRabat] [decimal](5, 2) NULL,
	[TrN_Rabat] [decimal](5, 2) NULL,
	[TrN_Zaokraglenie] [decimal](7, 2) NULL,
	[TrN_Zaksiegowano] [tinyint] NULL,
	[TrN_NieKsiegowac] [tinyint] NULL,
	[TrN_DataKsiegowania] [int] NULL,
	[TrN_Stan] [smallint] NULL,
	[TrN_LicznikKopii] [smallint] NULL,
	[TrN_SposobDostawy] [varchar](20) NULL,
	[TrN_MagZTyp] [smallint] NULL,
	[TrN_MagZFirma] [int] NULL,
	[TrN_MagZNumer] [int] NULL,
	[TrN_MagZLp] [smallint] NULL,
	[TrN_MagDTyp] [smallint] NULL,
	[TrN_MagDFirma] [int] NULL,
	[TrN_MagDNumer] [int] NULL,
	[TrN_MagDLp] [smallint] NULL,
	[TrN_OpeTypW] [smallint] NULL,
	[TrN_OpeFirmaW] [int] NULL,
	[TrN_OpeNumerW] [int] NULL,
	[TrN_OpeLpW] [smallint] NULL,
	[TrN_OpeTypZ] [smallint] NULL,
	[TrN_OpeFirmaZ] [int] NULL,
	[TrN_OpeNumerZ] [int] NULL,
	[TrN_OpeLpZ] [smallint] NULL,
	[TrN_OpeTypR] [smallint] NULL,
	[TrN_OpeFirmaR] [int] NULL,
	[TrN_OpeNumerR] [int] NULL,
	[TrN_OpeLpR] [smallint] NULL,
	[TrN_OdoTyp] [smallint] NULL,
	[TrN_OdoFirma] [int] NULL,
	[TrN_OdoNumer] [int] NULL,
	[TrN_OdoLp] [smallint] NULL,
	[TrN_Waluta] [varchar](3) NULL,
	[TrN_NrKursu] [smallint] NULL,
	[TrN_KursM] [decimal](5, 0) NULL,
	[TrN_KursL] [decimal](15, 10) NULL,
	[TrN_NettoR] [decimal](15, 2) NULL,
	[TrN_NettoP] [decimal](15, 2) NULL,
	[TrN_VatR] [decimal](15, 2) NULL,
	[TrN_VatP] [decimal](15, 2) NULL,
	[TrN_FrsID] [int] NULL,
	[TrN_CechaOpis] [varchar](250) NULL,
	[TrN_RokMiesiac] [int] NULL,
	[TrN_Aktywny] [int] NULL,
	[TrN_Wsk] [tinyint] NULL,
	[TrN_KarTyp] [smallint] NULL,
	[TrN_KarFirma] [int] NULL,
	[TrN_KarNumer] [int] NULL,
	[TrN_KarLp] [smallint] NULL,
	[TrN_KnDTyp] [smallint] NULL,
	[TrN_KnDFirma] [int] NULL,
	[TrN_KnDNumer] [int] NULL,
	[TrN_KnDLp] [smallint] NULL,
	[TrN_TypSumyPlatnosci] [tinyint] NULL,
	[TrN_WartoscDPPrzed] [decimal](15, 2) NULL,
	[TrN_WartoscDPPo] [decimal](15, 2) NULL,
	[TrN_ZmodyfikowanoZasob] [tinyint] NULL,
	[TrN_Url] [varchar](255) NULL,
	[TrN_RabatW] [decimal](15, 2) NULL,
	[TrN_Termin] [int] NULL,
	[TrN_DataWystOrg] [int] NULL,
	[TrN_DataSprOrg] [int] NULL,
	[TrN_FiaskoID] [int] NULL,
	[TrN_MiejsceZaladunku] [varchar](255) NULL,
	[TrN_MiejscePrzeznaczenia] [varchar](255) NULL,
	[TrN_RodzajTransportu] [varchar](255) NULL,
	[TrN_DataWysylki] [int] NULL,
	[TrN_InfoDlaUC] [varchar](2000) NULL,
	[TrN_Waga] [decimal](12, 3) NULL,
	[TrN_WJm] [varchar](5) NULL,
	[TrN_NumerSAD] [varchar](30) NULL,
	[TrN_WartoscWal] [decimal](15, 2) NULL,
	[TrN_OpeTypM] [smallint] NULL,
	[TrN_OpeFirmaM] [int] NULL,
	[TrN_OpeNumerM] [int] NULL,
	[TrN_OpeLpM] [smallint] NULL,
	[TrN_TypEdycjiVat] [tinyint] NULL,
	[TrN_IncotermsSymbol] [varchar](4) NULL,
	[TrN_IncotermsMiejsce] [varchar](255) NULL,
	[TrN_WagaBrutto] [decimal](12, 3) NULL,
	[TrN_OddDokId] [int] NULL,
	[TrN_DataOdb] [int] NULL,
	[TrN_DataRoz] [int] NULL,
	[TrN_OpiTyp] [smallint] NULL,
	[TrN_OpiFirma] [int] NULL,
	[TrN_OpiNumer] [int] NULL,
	[TrN_OpiLp] [smallint] NULL,
	[TrN_KrajPrzezWys] [varchar](2) NULL,
	[TrN_KodRodzajuTransportu] [varchar](2) NULL,
	[TrN_KodRodzajuTransakcji] [varchar](2) NULL,
	[TrN_RolnikRyczalt] [tinyint] NULL,
	[TrN_RozliczacP] [tinyint] NULL,
	[TrN_KorektaOdlicz] [tinyint] NULL,
	[TrN_Struktura] [tinyint] NULL,
	[TrN_Wyslano] [tinyint] NULL,
	[TrN_NrKursuPierw] [smallint] NULL,
	[TrN_KursMPierw] [decimal](5, 0) NULL,
	[TrN_KursLPierw] [decimal](15, 10) NULL,
	[TrN_Promocje] [int] NULL,
	[TrN_DataMag] [int] NULL,
	[TrN_DataOdprawyPotwierdzenia] [int] NULL,
	[TrN_PotwierdzenieOdbioru] [tinyint] NULL,
	[TrN_RabatPromocyjnyGlobalny] [decimal](15, 4) NULL,
	[TrN_Platnosci] [tinyint] NULL,
	[TrN_ZwroconoCalaIlosc] [tinyint] NULL,
	[TrN_TerminRozliczeniaKaucji] [int] NULL,
	[TrN_KnPTyp] [smallint] NULL,
	[TrN_KnPNumer] [int] NULL,
	[TrN_AdPNumer] [int] NULL,
	[TrN_LastMod] [int] NULL,
	[TrN_OddZakazPAFA] [smallint] NULL,
	[TrN_AktualizujKaucje] [tinyint] NULL,
	[TrN_StRIdW] [int] NULL,
	[TrN_WsSCHTyp] [smallint] NULL,
	[TrN_WsSCHNumer] [int] NULL,
	[TrN_WsStosujSchemat] [tinyint] NULL,
	[TrN_WsDziennik] [varchar](5) NULL,
	[TrN_WsStosujDziennik] [tinyint] NULL,
	[TrN_KosztUstalono] [tinyint] NULL,
	[TrN_Zrodlo] [int] NULL,
	[TrN_Intrastat] [tinyint] NULL,
	[TrN_IstRok] [smallint] NULL,
	[TrN_IstMiesiac] [smallint] NULL,
	[TrN_PrjId] [int] NULL,
	[TrN_KnSTypD] [smallint] NULL,
	[TrN_KnSFirmaD] [int] NULL,
	[TrN_KnSNumerD] [int] NULL,
	[TrN_KnSLpD] [smallint] NULL,
	[TrN_KnSTypP] [smallint] NULL,
	[TrN_KnSFirmaP] [int] NULL,
	[TrN_KnSNumerP] [int] NULL,
	[TrN_KnSLpP] [smallint] NULL,
	[TrN_GodzinaWystawienia] [int] NULL,
	[TrN_FrmNumer] [int] NULL,
	[TrN_StanDokMag] [smallint] NULL,
	[TrN_GenDokMag] [smallint] NULL,
	[TrN_PromocjePar] [tinyint] NULL,
	[TrN_PrzywracajRezerwacje] [tinyint] NULL,
	[TrN_FormatkaCyr] [tinyint] NULL,
	[TrN_ZewnetrznySys] [int] NULL,
	[TrN_WtrID] [int] NULL,
	[TrN_WtrProgID] [int] NULL,
	[TrN_TypDatyKor] [tinyint] NULL,
	[TrN_DataOdKor] [int] NULL,
	[TrN_DataDoKor] [int] NULL,
	[TrN_RodzajKor] [tinyint] NULL,
	[TrN_VatZDPeDNumer] [int] NULL,
	[TrN_VatZDPeDLp] [smallint] NULL,
	[TrN_PrzyczynaKorekty] [varchar](255) NULL,
	[TrN_KatDatyOP] [tinyint] NULL,
	[TrN_DataPO] [int] NULL,
	[TrN_DataDostawy] [int] NULL,
	[TrN_NumerRaportu] [int] NULL,
	[TrN_NumerFiskalny] [int] NULL,
	[TrN_WMS] [int] NULL,
	[TrN_PrzyczynaZW] [varchar](255) NULL,
	[TrN_PodstawaZW] [tinyint] NULL,
	[TrN_JPKFA] [tinyint] NULL,
	[TrN_VATNalOd] [tinyint] NULL,
	[TrN_Punkty] [decimal](11, 2) NULL,
	[TrN_OpeTypZM] [smallint] NULL,
	[TrN_OpeNumerZM] [int] NULL,
	[TrN_TStampZM] [int] NULL,
	[TrN_OpeTypZFR] [smallint] NULL,
	[TrN_OpeNumerZFR] [int] NULL,
	[TrN_TStampZFR] [int] NULL,
	[TrN_ZatwMerytorycznie] [tinyint] NULL,
	[TrN_ZatwFormalnoRach] [tinyint] NULL,
	[TrN_NrDrukarki] [varchar](32) NULL,
	[TrN_DataWplywu] [int] NULL,
	[TrN_PodzialPlatNiePytaj] [tinyint] NULL,
	[TrN_DataWplywuFA] [int] NULL,
	[TrN_MetodaKasowa] [tinyint] NULL,
	[TrN_KorektaDanych] [tinyint] NULL,
	[TrN_KKGNumer] [int] NULL,
	[TrN_KKDNumer] [int] NULL,
	[TrN_KKPNumer] [int] NULL,
	[TrN_KAGNumer] [int] NULL,
	[TrN_KADNumer] [int] NULL,
	[TrN_KAPNumer] [int] NULL,
	[TrN_ProceduraUproszcz] [tinyint] NULL,
	[TrN_OCR] [tinyint] NULL,
	[TrN_SposobRozbiciaKosztow] [tinyint] NULL,
	[TrN_OperatorPOS] [int] NULL,
	[TrN_GUID] [varchar](36) NULL,
	[TrN_MPP] [tinyint] NULL,
	[TrN_JestLimitCelowy] [tinyint] NULL,
	[TrN_DokTypJPK] [varchar](50) NULL,
	[TrN_OplataSpozFlaga] [tinyint] NULL,
	[TrN_UmNId] [int] NULL,
	[TrN_ProceduraOSS] [tinyint] NULL,
	[TrN_RozliczacVIU] [tinyint] NULL,
	[TrN_KorektaVIU] [tinyint] NULL,
	[TrN_DeklKwartalKVIU] [tinyint] NULL,
	[TrN_DeklRokKVIU] [smallint] NULL,
	[TrN_KrajWydania] [varchar](2) NULL,
	[TrN_KrajWydIdentPod] [varchar](15) NULL,
	[TrN_KrajWydIdentPodVAT] [tinyint] NULL,
	[TrN_KSeFWyslij] [tinyint] NULL,
	[TrN_KSeFNumerOrg] [varchar](50) NULL,
	[TrN_IdOrg] [int] NULL,
	[TrN_KSeFZweryfikowany] [tinyint] NULL,
  CONSTRAINT [TrN_Primary] PRIMARY KEY CLUSTERED ([TrN_GIDNumer])
)
GO

CREATE TABLE [CDN].[TraPlat](
	[TrP_GIDTyp] [smallint] NOT NULL,
	[TrP_GIDFirma] [int] NULL,
	[TrP_GIDNumer] [int] NOT NULL,
	[TrP_GIDLp] [smallint] NOT NULL,
	[TrP_KntTyp] [smallint] NULL,
	[TrP_KntFirma] [int] NULL,
	[TrP_KntNumer] [int] NULL,
	[TrP_KntLp] [smallint] NULL,
	[TrP_AkwTyp] [smallint] NULL,
	[TrP_AkwFirma] [int] NULL,
	[TrP_AkwNumer] [int] NULL,
	[TrP_AkwLp] [smallint] NULL,
	[TrP_Waluta] [varchar](3) NULL,
	[TrP_NrKursu] [smallint] NULL,
	[TrP_KursM] [decimal](5, 0) NULL,
	[TrP_KursL] [decimal](15, 10) NULL,
	[TrP_Typ] [smallint] NULL,
	[TrP_Termin] [int] NULL,
	[TrP_FormaNr] [tinyint] NULL,
	[TrP_FormaNazwa] [varchar](15) NULL,
	[TrP_Kwota] [decimal](15, 2) NULL,
	[TrP_Pozostaje] [decimal](15, 2) NULL,
	[TrP_Rozliczona] [tinyint] NULL,
	[TrP_Status] [smallint] NULL,
	[TrP_OpeWTyp] [smallint] NULL,
	[TrP_OpeWFirma] [int] NULL,
	[TrP_OpeWNumer] [int] NULL,
	[TrP_OpeWLp] [smallint] NULL,
	[TrP_Notatki] [varchar](200) NULL,
	[TrP_SpiTyp] [smallint] NULL,
	[TrP_SpiFirma] [int] NULL,
	[TrP_SpiNumer] [int] NULL,
	[TrP_SpiLp] [smallint] NULL,
	[TrP_KARTyp] [smallint] NULL,
	[TrP_KARFirma] [int] NULL,
	[TrP_KARNumer] [int] NULL,
	[TrP_KARLp] [smallint] NULL,
	[TrP_NrKonta] [smallint] NULL,
	[TrP_SpodziewanyTermin] [int] NULL,
	[TrP_SEPA] [tinyint] NULL,
	[TrP_ExpId] [int] NULL,
	[TrP_ExpLin] [int] NULL,
	[TrP_KwotaSys] [decimal](15, 2) NULL,
	[TrP_PozostajeSys] [decimal](15, 2) NULL,
	[TrP_KnANumer] [int] NULL,
	[TrP_CzasModyfikacji] [int] NULL,
	[TrP_Rodzaj] [tinyint] NULL,
	[TrP_ZewnetrznyId] [int] NULL,
	[TrP_CDCMsgId] [varchar](50) NULL,
	[TrP_CDCOrgInstrId] [varchar](35) NULL,
	[TrP_CDCExpTimestamp] [int] NULL,
	[TrP_OpeCDCTyp] [smallint] NULL,
	[TrP_OpeCDCFirma] [int] NULL,
	[TrP_OpeCDCNumer] [int] NULL,
	[TrP_OpeCDCLp] [smallint] NULL,
	[TrP_CDCStatusKod] [varchar](35) NULL,
	[TrP_CDCStatusOpis] [varchar](255) NULL,
	[TrP_CDCStatusTimestamp] [int] NULL,
	[TrP_MaksymalnyTermin] [int] NULL,
	[TrP_DataWysylki] [int] NULL,
	[TrP_JestLimitCelowy] [tinyint] NULL,
	[TrP_SplitPayment] [tinyint] NULL,
	[TrP_SPKwotaVAT] [decimal](15, 2) NULL,
	[TrP_SPNip] [varchar](20) NULL,
	[TrP_SPDokument] [varchar](40) NULL,
	[TrP_TerminPoProlongacie] [int] NULL,
	[TrP_ProlZrdTyp] [smallint] NULL,
	[TrP_ProlZrdFirma] [int] NULL,
	[TrP_ProlZrdNumer] [int] NULL,
	[TrP_ProlZrdLp] [smallint] NULL,
	[TrP_PrleLP] [int] NULL,
	[TrP_RachBank] [int] NULL,
	[TrP_ZrdTyp] [smallint] NULL,
	[TrP_ZrdFirma] [int] NULL,
	[TrP_ZrdNumer] [int] NULL,
	[TrP_ZrdLp] [smallint] NULL,
	[TrP_KorektaDanych] [tinyint] NULL,
	[TrP_BbonId] [int] NULL,
	[TrP_EndToEndId] [varchar](20) NULL,
	[TrP_DataRozliczenia] [int] NULL,
	[TrP_CzySprawaSporna] [tinyint] NULL,
	[TrP_SprawaSpornaId] [smallint] NULL,
	[TrP_CDCTaskId] [varchar](256) NULL,
	[TrP_LastMod] [int] NULL,
	[TrP_ProlRodzaj] [tinyint] NULL,
	[TrP_ProlObiTyp] [smallint] NULL,
	[TrP_ProlObiFirma] [int] NULL,
	[TrP_ProlObiNumer] [int] NULL,
	[TrP_ProlObiLp] [smallint] NULL,
  CONSTRAINT [TrP_Primary] PRIMARY KEY CLUSTERED ([TrP_GIDTyp],[TrP_GIDNumer],[TrP_GIDLp])
)
GO